"""Assembles a tarball containing every converted fixture module (each
placed at fixtures/<fixture directory name>/, see _fixture_dir_name) plus a
root MODULE.bazel that depends on all of them via local_path_override.

See docs/architecture/build-verification.md: unpacking this tarball and
running `bazel build`/`bazel test` from its root is how we validate that
converted fixture modules are genuinely independent — and, since they're
all real bazel_deps of the same root module, that they can depend on and
build against each other as bazelifier converts more projects.

The layout is staged as a directory first, then that one directory is
archived. Assembling it in the mtree instead — one `mtree_spec`/
`mtree_mutate` pair per entry, concatenated — is what this used to do, and
it made the tarball's layout a property of how N separate mtrees combine
rather than of anything you can look at. Three distinct bsdtar behaviors
had to be worked around to get it right: entry ordering deciding whether a
root file landed at the root or inside the last-seen directory, duplicate
synthesized parent-directory entries producing a nested `fixtures/fixtures/`,
and `package_dir` being unable to rename a basename. Each failed by
producing a subtly wrong tarball rather than an error. Staging on disk
removes the class: one directory in, one mtree out.
"""

load("@tar.bzl//tar:mtree.bzl", "mtree_mutate", "mtree_spec")
load("@tar.bzl//tar:tar.bzl", "tar")

# Every fixture's own generated MODULE.bazel / BUILD.bazel doesn't exist
# until the convert_cmake_project action actually runs, so the root
# MODULE.bazel/BUILD.bazel below — which need every fixture's real
# module_name and executable target names — can't be assembled from
# Starlark attrs at analysis time. They're generated by a script run
# inside the same execution-time shell action that stages the fixtures,
# reading each fixture's own generated output directly. This also removes
# the module_name/expected_targets duplication that used to live in every
# fixture's BUILD.bazel: those facts now have exactly one source, the
# translator's own generated output, so they can't drift from it.
_GENERATE_ROOT_FILES_SCRIPT = """#!/usr/bin/env bash
set -euo pipefail

out_dir="$1"
root_module_name="$2"
shift 2
fixture_dirs=("$@")

{
  echo "module("
  echo "    name = \\"${root_module_name}\\","
  echo "    version = \\"0.0.0\\","
  echo ")"
  echo
  echo "bazel_dep(name = \\"rules_shell\\", version = \\"0.8.0\\")"
  echo
} > "${out_dir}/MODULE.bazel"

{
  echo "load(\\"@rules_shell//shell:sh_test.bzl\\", \\"sh_test\\")"
  echo
} > "${out_dir}/BUILD.bazel"

test_labels=()

for fixture_dir in "${fixture_dirs[@]}"; do
  fixture_name="$(basename "${fixture_dir}")"
  module_bazel="${out_dir}/fixtures/${fixture_dir}/MODULE.bazel"
  build_bazel="${out_dir}/fixtures/${fixture_dir}/BUILD.bazel"

  # module(name = "...") is always rendered exactly this way — see
  # codegen::render_module_bazel — so a plain sed extraction is reliable
  # rather than needing a real Starlark parser here.
  module_name="$(sed -n 's/^ *name = "\\(.*\\)",$/\\1/p' "${module_bazel}" | head -1)"
  if [[ -z "${module_name}" ]]; then
    echo "generate_root_files: could not find module name in ${module_bazel}" >&2
    exit 1
  fi

  {
    echo "bazel_dep(name = \\"${module_name}\\", version = \\"0.0.0\\")"
    echo "local_path_override("
    echo "    module_name = \\"${module_name}\\","
    echo "    path = \\"fixtures/${fixture_dir}\\","
    echo ")"
    echo
  } >> "${out_dir}/MODULE.bazel"

  # cc_binary(name = "...") is likewise always rendered this way — see
  # codegen::render_cc_rule via rule_name — so every executable target
  # name (and only executable target names) can be read straight back out
  # of the generated BUILD.bazel. Each one's ground-truth artifact was
  # copied under the same name by copy_ground_truth_artifacts (CMake's
  # default OUTPUT_NAME behavior), so no separate listing of
  # ground_truth/ is needed, and — unlike listing ground_truth/ itself —
  # this doesn't also pick up library artifacts (e.g. libgreet.a) that
  # compare_runtime_output.sh can't execute.
  while IFS= read -r target_name; do
    test_name="${fixture_name}_${target_name}_matches_ground_truth"
    test_labels+=("        \\":${test_name}\\",")
    {
      echo "sh_test("
      echo "    name = \\"${test_name}\\","
      echo "    srcs = [\\"compare_runtime_output.sh\\"],"
      echo "    args = ["
      echo "        \\"\\$(location @${module_name}//:${target_name})\\","
      echo "        \\"\\$(location @${module_name}//ground_truth:${target_name})\\","
      echo "        \\"${module_name}+/needs_attention\\","
      echo "    ],"
      echo "    data = ["
      echo "        \\"@${module_name}//:${target_name}\\","
      echo "        \\"@${module_name}//ground_truth:${target_name}\\","
      echo "        \\"@${module_name}//needs_attention:all\\","
      echo "    ],"
      echo ")"
      echo
    } >> "${out_dir}/BUILD.bazel"
  done < <(sed -n 's/^cc_binary($/&/p; /^cc_binary($/,/^)$/ s/^ *name = "\\(.*\\)",$/\\1/p' "${build_bazel}" | grep -v '^cc_binary($')
done

{
  echo "test_suite("
  echo "    name = \\"all_ground_truth_comparisons\\","
  echo "    tests = ["
  printf '%s\\n' "${test_labels[@]}"
  echo "    ],"
  echo ")"
} >> "${out_dir}/BUILD.bazel"
"""

def _fixture_dir_name(label):
    """Returns the name used for a fixture's directory inside the tarball.

    This is the basename of the package the convert_cmake_project target
    lives in (e.g. "001-hello-world"), not the target's own name (which is
    conventionally just "converted" for every fixture, so it can't be used
    to distinguish them).
    """
    return label.package.rsplit("/", 1)[-1]

def _validation_tree_impl(ctx):
    out = ctx.actions.declare_directory(ctx.attr.name)

    generate_script = ctx.actions.declare_file(ctx.attr.name + "_generate_root_files.sh")
    ctx.actions.write(generate_script, _GENERATE_ROOT_FILES_SCRIPT, is_executable = True)

    # `cp` without -p takes the source's permission bits but not its
    # timestamps, which is what the archive wants: the comparison script
    # stays executable, while every entry's mtime comes from mtree_spec
    # rather than from whatever the execroot happened to hold.
    commands = [
        "set -e",
        "mkdir -p {}/fixtures".format(out.path),
        "cp {} {}/compare_runtime_output.sh".format(ctx.file.compare_script.path, out.path),
    ]

    inputs = [generate_script, ctx.file.compare_script]
    fixture_dirs = []
    for target in ctx.attr.fixtures:
        # A convert_cmake_project target's DefaultInfo is exactly the one
        # tree artifact holding its generated module.
        tree = target[DefaultInfo].files.to_list()[0]
        inputs.append(tree)
        fixture_dir = _fixture_dir_name(target.label)
        fixture_dirs.append(fixture_dir)
        staged = "{}/fixtures/{}".format(out.path, fixture_dir)
        commands.append("mkdir -p {}".format(staged))
        commands.append("cp -R {}/. {}/".format(tree.path, staged))

    commands.append("{} {} {} {}".format(
        generate_script.path,
        out.path,
        ctx.attr.name_of_root_module,
        " ".join(fixture_dirs),
    ))

    ctx.actions.run_shell(
        outputs = [out],
        inputs = inputs,
        command = "\n".join(commands),
        mnemonic = "StageValidationWorkspace",
        progress_message = "Staging validation workspace %s" % ctx.attr.name,
    )

    return [DefaultInfo(files = depset([out]))]

_validation_tree = rule(
    implementation = _validation_tree_impl,
    doc = "Stages the unpacked workspace's exact layout as one directory.",
    attrs = {
        "compare_script": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The ground-truth comparison script, placed at the tarball root.",
        ),
        "fixtures": attr.label_list(
            mandatory = True,
            providers = [DefaultInfo],
            doc = "convert_cmake_project targets to stage under fixtures/.",
        ),
        "name_of_root_module": attr.string(
            mandatory = True,
            doc = "Name for the generated root MODULE.bazel's own module() declaration. Never referenced by a fixture — the root module is the thing being built from, not depended on — so it only has to be a valid module name.",
        ),
    },
)

def validation_workspace(name, fixtures, **kwargs):
    """Packages `fixtures` (convert_cmake_project targets) into a tarball.

    Each fixture lands at `fixtures/<fixture directory name>/` inside the
    tarball (see `_fixture_dir_name`). The tarball's root also contains a
    MODULE.bazel that bazel_deps on every fixture via local_path_override,
    so unpacking the tarball and running `bazel build //...`/`bazel test
    //...` from its root builds/tests every converted fixture — and lets
    fixtures depend on each other, once bazelifier converts projects with
    real inter-project dependencies.

    Args:
        name: name of the tar target producing the tarball.
        fixtures: list of convert_cmake_project target labels to include.
        **kwargs: passed through to the underlying tar rule.
    """
    tree_name = name + "_tree"
    _validation_tree(
        name = tree_name,
        compare_script = "//translator/build_defs:compare_runtime_output.sh",
        fixtures = fixtures,
        name_of_root_module = name,
    )

    spec_name = name + "_mtree"
    mtree_spec(
        name = spec_name,
        srcs = [":" + tree_name],
    )

    # The staged directory's own path is the only prefix to strip: every
    # entry is already at its final location beneath it.
    rooted_name = name + "_mtree_rooted"
    mtree_mutate(
        name = rooted_name,
        mtree = ":" + spec_name,
        strip_prefix = native.package_name() + "/" + tree_name,
    )

    tar(
        name = name,
        srcs = [":" + tree_name],
        mtree = ":" + rooted_name,
        **kwargs
    )
