"""Assembles a tarball containing every converted fixture module (each
placed at fixtures/<fixture directory name>/, see _fixture_dir_name) plus a
root MODULE.bazel that depends on all of them via local_path_override.

See docs/architecture/build-verification.md: unpacking this tarball and
running `bazel build`/`bazel test` from its root is how we validate that
converted fixture modules are genuinely independent — and, since they're
all real bazel_deps of the same root module, that they can depend on and
build against each other as bazelifier converts more projects.

The layout is staged as a directory first, then that one directory is
archived. Assembling it in the mtree instead — one `mtree_spec`/
`mtree_mutate` pair per entry, concatenated — is what this used to do, and
it made the tarball's layout a property of how N separate mtrees combine
rather than of anything you can look at. Three distinct bsdtar behaviors
had to be worked around to get it right: entry ordering deciding whether a
root file landed at the root or inside the last-seen directory, duplicate
synthesized parent-directory entries producing a nested `fixtures/fixtures/`,
and `package_dir` being unable to rename a basename. Each failed by
producing a subtly wrong tarball rather than an error. Staging on disk
removes the class: one directory in, one mtree out.

`cc_config` is deliberately NOT staged here, and no `bazel_dep`/
`local_path_override` for it is emitted into the root MODULE.bazel — even
though every generated `config_header` rule depends on it and it is not
published to any registry yet (bzl-fxa.4). Unpacking the tarball and
building a config_header fixture therefore fails module resolution with
`module cc_config@0.0.0 not found in registries` until the validation
invocation supplies it:

    bazel test //:all_ground_truth_comparisons --keep_going \\
        --override_module=cc_config=<bazelifier-checkout>/cc_config

`--keep_going` because one fixture failing to BUILD otherwise aborts the
run and every other fixture reports NO STATUS — no signal from any of them.

That error is the expected state of the tarball, not a defect in it. Adding
the override to the generated MODULE.bazel would bake an absolute path to a
bazelifier checkout into the deliverable, and staging a copy of cc_config
inside the tarball would fork it per conversion; both destroy the property
the unpack step exists to prove — that the tarball is path-free and
portable, resolving cc_config the way a real consumer would, from a
registry. The flag stays on our harness. See
docs/architecture/build-verification.md ("Unpack, fully outside this repo").
"""

load("@tar.bzl//tar:mtree.bzl", "mtree_mutate", "mtree_spec")
load("@tar.bzl//tar:tar.bzl", "tar")

# Every fixture's own generated MODULE.bazel / BUILD.bazel doesn't exist
# until the convert_cmake_project action actually runs, so the root
# MODULE.bazel/BUILD.bazel below — which need every fixture's real
# module_name and executable target names — can't be assembled from
# Starlark attrs at analysis time. They're generated by a script run
# inside the same execution-time shell action that stages the fixtures,
# reading each fixture's own generated output directly. This also removes
# the module_name/expected_targets duplication that used to live in every
# fixture's BUILD.bazel: those facts now have exactly one source, the
# translator's own generated output, so they can't drift from it.
_GENERATE_ROOT_FILES_SCRIPT = """#!/usr/bin/env bash
set -euo pipefail

out_dir="$1"
root_module_name="$2"
shift 2
fixture_dirs=("$@")

{
  echo "module("
  echo "    name = \\"${root_module_name}\\","
  echo "    version = \\"0.0.0\\","
  echo ")"
  echo
  echo "bazel_dep(name = \\"rules_shell\\", version = \\"0.8.0\\")"
  echo
  # This comment ships in the unpacked workspace on purpose: when a
  # config_header fixture fails with "module cc_config@0.0.0 not found in
  # registries", Bazel names this file in the dependency chain, so the
  # answer has to be readable from here — the repo's docs are not in view.
  echo "# NOTE: no bazel_dep/local_path_override for cc_config appears below,"
  echo "# and that is deliberate. Generated config_header rules depend on"
  echo "# cc_config, which is not published to a registry yet, so building"
  echo "# them from this unpacked root requires:"
  echo "#"
  echo "#     bazel test //:all_ground_truth_comparisons --keep_going \\\\"
  echo "#         --override_module=cc_config=<bazelifier-checkout>/cc_config"
  echo "#"
  echo "# The flag lives on the validation invocation rather than in this file"
  echo "# so the tarball stays path-free and portable: a real consumer would"
  echo "# resolve cc_config from a registry. Do not \\"fix\\" this by writing an"
  echo "# override here or by copying cc_config into the tarball."
  echo
} > "${out_dir}/MODULE.bazel"

{
  echo "load(\\"@rules_shell//shell:sh_test.bzl\\", \\"sh_test\\")"
  echo
} > "${out_dir}/BUILD.bazel"

test_labels=()

for fixture_dir in "${fixture_dirs[@]}"; do
  fixture_name="$(basename "${fixture_dir}")"
  module_bazel="${out_dir}/fixtures/${fixture_dir}/MODULE.bazel"
  build_bazel="${out_dir}/fixtures/${fixture_dir}/BUILD.bazel"

  # module(name = "...") is always rendered exactly this way — see
  # codegen::render_module_bazel — so a plain sed extraction is reliable
  # rather than needing a real Starlark parser here.
  module_name="$(sed -n 's/^ *name = "\\(.*\\)",$/\\1/p' "${module_bazel}" | head -1)"
  if [[ -z "${module_name}" ]]; then
    echo "generate_root_files: could not find module name in ${module_bazel}" >&2
    exit 1
  fi

  {
    echo "bazel_dep(name = \\"${module_name}\\", version = \\"0.0.0\\")"
    echo "local_path_override("
    echo "    module_name = \\"${module_name}\\","
    echo "    path = \\"fixtures/${fixture_dir}\\","
    echo ")"
    echo
  } >> "${out_dir}/MODULE.bazel"

  # sh_test(name = "<binary>_test") is how the translator emits a
  # CTest-registered test (see codegen::render_sh_test): it runs the binary
  # at its declared WORKING_DIRECTORY with runtime data staged and asserts
  # the project's own PASS_REGULAR_EXPRESSION. A binary with such a test is
  # validated by it, NOT by the naive ground-truth stdout comparison below —
  # which for a data-driven test (tinyxml2's xmltest reads resources/) would
  # run both binaries with no data, see them fail identically, and false-pass.
  # So: collect the tested binaries, skip their comparison, and add their own
  # test to the suite instead.
  # The binary is read from the rule's FIRST arg, not by stripping `_test` off
  # its name. codegen renders `name = "<ctest test name>_test"`, and a CTest
  # test's name need not match the binary it runs — so the strip recovers the
  # TEST name and the skip below silently misses, emitting the very
  # false-passing comparison this block exists to suppress. It only ever
  # looked correct because tinyxml2 names its test `xmltest` after its binary
  # `xmltest`; fixture 022's `app_test` on binary `app` breaks it.
  # Read from the module's own TARGETS manifest, not by regexing its
  # BUILD.bazel. The harness needs three facts — which binaries exist, which
  # tests wrap them, and which config-header assertions to run — and used to
  # recover all three with sed over generated Starlark, coupling it to
  # codegen's exact formatting. A formatting change (the intended
  # buildifier-on-output pass is the obvious one) would match nothing, and a
  # sed matching nothing yields no tests rather than an error. See bzl-dmf and
  # main.rs::write_targets_manifest.
  manifest="${out_dir}/fixtures/${fixture_dir}/TARGETS"
  if [[ ! -f "${manifest}" ]]; then
    echo "generate_root_files: ${fixture_dir} has no TARGETS manifest" >&2
    exit 1
  fi
  # Every fixture emits at least one target, so an empty manifest means the
  # translator stopped writing it rather than that there is nothing to check —
  # the difference between a suite that passes and one that looks at nothing.
  if [[ ! -s "${manifest}" ]]; then
    echo "generate_root_files: ${fixture_dir}'s TARGETS manifest is empty" >&2
    exit 1
  fi

  # A binary with its own CTest test is validated by that test, NOT by the
  # naive ground-truth stdout comparison: a data-driven test (tinyxml2's
  # xmltest reads resources/) run with no data would fail identically on both
  # sides and false-pass. The manifest names the binary each test wraps, so
  # this no longer depends on a test being named after its binary — it need
  # not be (fixture 022's app_test runs app).
  tested_binaries=" "
  while read -r kind name target; do
    case "${kind}" in
      test)
        test_labels+=("        \\"@${module_name}//:${name}\\",")
        tested_binaries="${tested_binaries}${target} "
        ;;
      assertion)
        test_labels+=("        \\"@${module_name}//:${name}\\",")
        ;;
    esac
  done < "${manifest}"

  # cc_binary(name = "...") is likewise always rendered this way — see
  # codegen::render_cc_rule via rule_name — so every executable target
  # name (and only executable target names) can be read straight back out
  # of the generated BUILD.bazel. Each one's ground-truth artifact was
  # copied under the same name by copy_ground_truth_artifacts (CMake's
  # default OUTPUT_NAME behavior), so no separate listing of
  # ground_truth/ is needed, and — unlike listing ground_truth/ itself —
  # this doesn't also pick up library artifacts (e.g. libgreet.a) that
  # compare_runtime_output.sh can't execute.
  while IFS= read -r target_name; do
    # Skip a binary that has its own CTest test (see tested_binaries above).
    case "${tested_binaries}" in
      *" ${target_name} "*) continue ;;
    esac
    test_name="${fixture_name}_${target_name}_matches_ground_truth"
    test_labels+=("        \\":${test_name}\\",")
    {
      echo "sh_test("
      echo "    name = \\"${test_name}\\","
      echo "    srcs = [\\"compare_runtime_output.sh\\"],"
      echo "    args = ["
      echo "        \\"\\$(location @${module_name}//:${target_name})\\","
      echo "        \\"\\$(location @${module_name}//ground_truth:${target_name})\\","
      echo "        \\"${module_name}+/needs_attention\\","
      echo "    ],"
      # ground_truth:shared_libs is the staged .so chain a dynamically linked
      # ground-truth binary needs at run time (empty for a static-only module).
      # It lands in ground_truth/ next to the binary, so the script derives
      # LD_LIBRARY_PATH from the binary's own dir — see compare_runtime_output.sh
      # and copy_ground_truth_artifacts (bzl-fxa.11).
      echo "    data = ["
      echo "        \\"@${module_name}//:${target_name}\\","
      echo "        \\"@${module_name}//ground_truth:${target_name}\\","
      echo "        \\"@${module_name}//ground_truth:shared_libs\\","
      echo "        \\"@${module_name}//needs_attention:all\\","
      echo "    ],"
      echo ")"
      echo
    } >> "${out_dir}/BUILD.bazel"
  done < <(awk '$1 == "binary" { print $2 }' "${manifest}")
done

# A sed extraction that matches nothing yields no tests, not an error — the
# suite then passes by looking at nothing, which is the failure this repo
# keeps producing (bzl-0pd was exactly it). Every fixture emits at least one
# cc_binary or sh_test, so an empty label set means the patterns stopped
# matching codegen's output rather than that there is nothing to check.
#
# This is a floor, not a substitute for bzl-dmf's real fix (a manifest the
# translator writes, instead of regexing its own formatting back out).
if [[ ${#test_labels[@]} -eq 0 ]]; then
  echo "generate_root_files: extracted ZERO test targets from ${#fixture_dirs[@]} fixture(s)." >&2
  echo "  The sed patterns above no longer match the translator's output —" >&2
  echo "  most likely codegen's formatting changed (see bzl-dmf). The suite" >&2
  echo "  would otherwise be generated empty and pass while checking nothing." >&2
  exit 1
fi

{
  echo "test_suite("
  echo "    name = \\"all_ground_truth_comparisons\\","
  echo "    tests = ["
  printf '%s\\n' "${test_labels[@]}"
  echo "    ],"
  echo ")"
} >> "${out_dir}/BUILD.bazel"
"""

def _fixture_dir_name(label):
    """Returns the name used for a fixture's directory inside the tarball.

    This is the basename of the package the convert_cmake_project target
    lives in (e.g. "001-hello-world"), not the target's own name (which is
    conventionally just "converted" for every fixture, so it can't be used
    to distinguish them).
    """
    return label.package.rsplit("/", 1)[-1]

def _validation_tree_impl(ctx):
    out = ctx.actions.declare_directory(ctx.attr.name)

    generate_script = ctx.actions.declare_file(ctx.attr.name + "_generate_root_files.sh")
    ctx.actions.write(generate_script, _GENERATE_ROOT_FILES_SCRIPT, is_executable = True)

    # `cp` without -p takes the source's permission bits but not its
    # timestamps, which is what the archive wants: the comparison script
    # stays executable, while every entry's mtime comes from mtree_spec
    # rather than from whatever the execroot happened to hold.
    commands = [
        "set -e",
        "mkdir -p {}/fixtures".format(out.path),
        "cp {} {}/compare_runtime_output.sh".format(ctx.file.compare_script.path, out.path),
    ]

    inputs = [generate_script, ctx.file.compare_script]
    fixture_dirs = []
    for target in ctx.attr.fixtures:
        # A convert_cmake_project target's DefaultInfo is exactly the one
        # tree artifact holding its generated module.
        tree = target[DefaultInfo].files.to_list()[0]
        inputs.append(tree)
        fixture_dir = _fixture_dir_name(target.label)
        fixture_dirs.append(fixture_dir)
        staged = "{}/fixtures/{}".format(out.path, fixture_dir)
        commands.append("mkdir -p {}".format(staged))
        commands.append("cp -R {}/. {}/".format(tree.path, staged))

    commands.append("{} {} {} {}".format(
        generate_script.path,
        out.path,
        ctx.attr.name_of_root_module,
        " ".join(fixture_dirs),
    ))

    ctx.actions.run_shell(
        outputs = [out],
        inputs = inputs,
        command = "\n".join(commands),
        mnemonic = "StageValidationWorkspace",
        progress_message = "Staging validation workspace %s" % ctx.attr.name,
    )

    return [DefaultInfo(files = depset([out]))]

_validation_tree = rule(
    implementation = _validation_tree_impl,
    doc = "Stages the unpacked workspace's exact layout as one directory.",
    attrs = {
        "compare_script": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The ground-truth comparison script, placed at the tarball root.",
        ),
        "fixtures": attr.label_list(
            mandatory = True,
            providers = [DefaultInfo],
            doc = "convert_cmake_project targets to stage under fixtures/.",
        ),
        "name_of_root_module": attr.string(
            mandatory = True,
            doc = "Name for the generated root MODULE.bazel's own module() declaration. Never referenced by a fixture — the root module is the thing being built from, not depended on — so it only has to be a valid module name.",
        ),
    },
)

def validation_workspace(name, fixtures, **kwargs):
    """Packages `fixtures` (convert_cmake_project targets) into a tarball.

    Each fixture lands at `fixtures/<fixture directory name>/` inside the
    tarball (see `_fixture_dir_name`). The tarball's root also contains a
    MODULE.bazel that bazel_deps on every fixture via local_path_override,
    so unpacking the tarball and running `bazel build //...`/`bazel test
    //...` from its root builds/tests every converted fixture — and lets
    fixtures depend on each other, once bazelifier converts projects with
    real inter-project dependencies.

    Args:
        name: name of the tar target producing the tarball.
        fixtures: list of convert_cmake_project target labels to include.
        **kwargs: passed through to the underlying tar rule.
    """
    tree_name = name + "_tree"
    _validation_tree(
        name = tree_name,
        compare_script = "//translator/build_defs:compare_runtime_output.sh",
        fixtures = fixtures,
        name_of_root_module = name,
    )

    spec_name = name + "_mtree"
    mtree_spec(
        name = spec_name,
        srcs = [":" + tree_name],
    )

    # The staged directory's own path is the only prefix to strip: every
    # entry is already at its final location beneath it.
    rooted_name = name + "_mtree_rooted"
    mtree_mutate(
        name = rooted_name,
        mtree = ":" + spec_name,
        strip_prefix = native.package_name() + "/" + tree_name,
    )

    tar(
        name = name,
        srcs = [":" + tree_name],
        mtree = ":" + rooted_name,
        **kwargs
    )
