//! The Autotools frontend: recovers a build graph from `make -n`.
//!
//! Where `cmake_api` reads a structured reply, this reads the build system's
//! **resolved command stream**. That is the closest autotools analogue to the
//! CMake File API, and it is the same KIND of thing — the build system's own
//! answer after configuration, not the input it was configured from:
//!
//! - `Makefile.am` is declarative and closest in intent, but is NOT resolved:
//!   `foo_LDADD = $(LIBINTL) $(top_builddir)/lib/lib$(PACKAGE).a` names
//!   variables only `configure` fills in, and automake conditionals and
//!   `SUBDIRS` recursion mean the declared graph is not the built one. Parsing
//!   it is the "read the source build files" path `cmake_api`'s module doc
//!   explicitly rejects.
//! - The generated `Makefile` IS resolved but is thousands of lines of make
//!   syntax with recursive expansion; consuming it means implementing enough
//!   of make to be correct.
//! - `make -n` prints exactly what the build would run, fully expanded, and in
//!   a stable command ORDER — more stable than the File API, which reports
//!   dependency order unstably (bzl-sjp). Not byte-identical: `-B` forces a
//!   `config.status --recheck` preamble, which is one reason `parse_commands`
//!   recognises only the programs that build something and ignores the rest.
//!
//! What the command stream does NOT carry is target NAMES. automake knows a
//! program is called `greeter` because `bin_PROGRAMS` says so; the stream only
//! shows `-o greeter`. So identity comes from a SECOND source, `make -p`'s
//! variable database, via [`declared_targets`] — a declaration, not an
//! inference. Deriving names from artifact paths was tried and abandoned:
//! stripping the `lib` prefix and the suffix collapsed GNU hello's
//! `bin_PROGRAMS = hello` and `noinst_LIBRARIES = lib/libhello.a` onto one
//! name, producing a module that could not load.

use std::collections::hash_map::Entry;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::configure_file::catalog_label;
use crate::error::Error;
use crate::headers::inject_headers_on_include_dirs;
use crate::needs_attention::{
    sources_outside_deliverable_needs_attention, unmapped_config_macros_needs_attention,
};
use crate::model::{BuildGraph, ConfigHeader, Discovery, ModuleInfo, Target, TargetKind};
use crate::paths::{absolutize, normalize_lexically};

/// One resolved command from the build stream, split into a program and its
/// arguments with shell noise already removed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct BuildCommand {
    pub(crate) program: String,
    pub(crate) args: Vec<String>,
    /// The directory this command runs in, absolute.
    ///
    /// Recursive make descends into each subdirectory and runs its commands
    /// from there, so a path in `args` is relative to THIS, not to the build
    /// root: xz's `src/xz` compiles `../common/tuklib_mbstr_width.c`, and
    /// fixture 002 compiles `../common/util.c`. Recording the directory is
    /// what makes those resolvable at all — `../common/util.c` is neither
    /// absolute nor module-relative, so emitting it verbatim produces a label
    /// that reaches above its own module, which codegen refuses.
    ///
    /// CMake+Ninja needs no equivalent: it runs every command from the build
    /// root, so its paths are already root-relative. This is a structural
    /// difference between the two build systems rather than an oversight in
    /// the CMake frontend.
    pub(crate) dir: PathBuf,
}

/// Converts an Autotools project, mirroring `cmake_api::discover`.
///
/// Three steps: the tree is CONFIGURED (so `make` has resolved variables to
/// report), then really BUILT (so ground-truth artifacts exist for the
/// equivalence check — see docs/architecture/build-verification.md), then
/// interrogated.
///
/// The interrogation comes AFTER the build, and the dry run uses `-B`. Both
/// halves are load-bearing: a dry run before the build exits 2 on a recursive
/// project, and a plain one after it prints nothing. See
/// docs/lore/make-n-answers-differently-before-and-after-a-build.md.
pub fn discover(
    source_dir: &Path,
    build_dir: &Path,
    _deliverable_root: &Path,
) -> Result<Discovery, Error> {
    configure(source_dir, build_dir)?;
    build(build_dir)?;

    let stream = dry_run(build_dir)?;
    let database = variable_database(build_dir)?;

    let vars = parse_variables(&database);
    let declared = declared_targets(&vars);

    // AC_CONFIG_HEADERS, from config.status — see parse_config_headers on why
    // not configure.ac. The template lives in the SOURCE tree (autoconf's
    // config.h.in is checked in or generated by autoheader at bootstrap
    // time), unlike CMake's, which a project can generate into the build dir.
    let mut config_headers = Vec::new();
    let mut needs_attention = Vec::new();
    let status = std::fs::read_to_string(build_dir.join("config.status")).unwrap_or_default();
    for (output, template) in parse_config_headers(&status) {
        let template_path = source_dir.join(&template);
        let Ok(text) = std::fs::read_to_string(&template_path) else {
            continue;
        };
        let (header, unmapped) = plan_config_header(&output, &template, &text, &vars);
        if !unmapped.is_empty() {
            needs_attention.push(unmapped_config_macros_needs_attention(
                &output, &template, &unmapped,
            ));
        }
        config_headers.push(header);
    }
    let project_name = vars
        .get("PACKAGE")
        .or_else(|| vars.get("PACKAGE_NAME"))
        .cloned()
        .unwrap_or_else(|| "project".to_string());
    let (mut graph, graph_needs_attention) = to_graph(
        &parse_commands(&stream, build_dir),
        &declared,
        &vars,
        &project_name,
        &absolutize(source_dir)?,
        &absolutize(build_dir)?,
    );
    graph.config_headers = config_headers;
    needs_attention.extend(graph_needs_attention);

    // The same header-staging passes the CMake frontend runs, and for the
    // same reasons: a header reachable on the include path is an input Bazel
    // must be told about, and a header beside its source is found by the
    // quoted-include rule that no build system reports. Neither is
    // CMake-specific — `headers` takes a `[Target]` and a source root and
    // knows nothing about where the graph came from.
    inject_headers_on_include_dirs(&mut graph.targets, &absolutize(source_dir)?);

    Ok(Discovery {
        graph,
        // Unmapped config macros, and sources that escaped the module. Two
        // gaps remain undetected — an external library the project links but
        // does not build, and a declared target `make` never produced — which
        // is honest now and wrong once it meets a project it cannot fully
        // convert. See bzl-yjn.5.
        needs_attention,
        module_root: source_dir.to_path_buf(),
    })
}

/// Runs `configure` in `build_dir`, out of tree.
///
/// Autotools supports building outside the source directory, which is what
/// keeps the source tree clean the way CMake's `-B` does.
fn configure(source_dir: &Path, build_dir: &Path) -> Result<(), Error> {
    std::fs::create_dir_all(build_dir)?;
    // Absolutized because the command runs with `current_dir(build_dir)`: a
    // caller-supplied source_dir is usually relative (Bazel passes an
    // execroot-relative path), and a relative path stops resolving the moment
    // the working directory changes. Same reason cmake_api absolutizes before
    // comparing paths.
    let configure = absolutize(source_dir)?.join("configure");
    let output = Command::new(&configure)
        .current_dir(build_dir)
        .output()
        .map_err(|e| {
            // A source tree with configure.ac but no configure has not been
            // bootstrapped; saying so beats "no such file or directory".
            if e.kind() == std::io::ErrorKind::NotFound {
                Error::ConfigureFailed {
                    stderr: format!(
                        "{} not found — the project ships configure.ac but has not been \
                         bootstrapped. Run autoreconf -i in the source tree first.",
                        configure.display()
                    ),
                }
            } else {
                Error::Io(e)
            }
        })?;
    if !output.status.success() {
        return Err(Error::ConfigureFailed {
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(())
}

/// Really builds the project, producing the ground-truth artifacts.
fn build(build_dir: &Path) -> Result<(), Error> {
    // Parallel: the build is the ground-truth capture, and nothing about it
    // needs to be serial. Measured 14s -> 2s on xz. `-j` with no argument
    // would be unbounded, which on a large project starves the machine, so
    // the core count is passed explicitly.
    let jobs = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(1);
    let output = Command::new("make")
        .arg(format!("-j{jobs}"))
        .current_dir(build_dir)
        .output()?;
    if !output.status.success() {
        return Err(Error::BuildFailed {
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(())
}

/// Runs `make -n` in a configured tree and returns its output.
///
/// The tree must already be configured, exactly as `cmake_api` requires an
/// already-configured build directory — `make -n` on an unconfigured tree
/// reports the rules that would regenerate `Makefile`, not the build.
pub(crate) fn dry_run(build_dir: &Path) -> Result<String, Error> {
    let output = Command::new("make")
        .arg("-n")
        // Force-rebuild: without it a built tree reports nothing to do. See
        // `discover` on why the tree must be built first anyway.
        .arg("-B")
        .current_dir(build_dir)
        .output()?;
    if !output.status.success() {
        return Err(Error::BuildFailed {
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Runs `make -p` and returns make's resolved variable database.
///
/// `-n` alongside `-p` so nothing is actually built; the database is a side
/// effect of make reading the tree, not of running it.
pub(crate) fn variable_database(build_dir: &Path) -> Result<String, Error> {
    let output = Command::new("make")
        .arg("-p")
        .arg("-n")
        .current_dir(build_dir)
        .output()?;
    // Not checking status: `make -p` exits nonzero on a tree with nothing to
    // do, having already printed the database, which is all this needs.
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// One target automake declared, recovered from a primary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DeclaredTarget {
    /// The name automake knows it by (`greeter`, `libshout.la`).
    pub(crate) name: String,
    /// The install-destination prefix of the primary that declared it
    /// (`bin`, `lib`, `noinst`, `check`). This is where the public/private
    /// signal lives — `noinst_` means built but never installed.
    pub(crate) destination: String,
    /// Which primary declared it, so linkage does not have to be guessed
    /// from a filename: `LTLIBRARIES` builds a shared library, `LIBRARIES`
    /// an archive.
    pub(crate) primary: String,
}

/// Parses `make -p` output into a variable map.
///
/// Split from [`variable_database`] so a frozen real capture can drive it
/// without a configured tree. Only `NAME = value` lines are kept; make's
/// database also contains rules, comments and `NAME := value` forms, none of
/// which carry automake's declarations.
pub(crate) fn parse_variables(database: &str) -> HashMap<String, String> {
    let mut vars = HashMap::new();
    for line in database.lines() {
        // Rules and comments both reach here; a leading tab means a recipe.
        if line.starts_with('\t') || line.starts_with('#') {
            continue;
        }
        let Some((name, value)) = line.split_once(" = ") else {
            continue;
        };
        if name.is_empty() || !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            continue;
        }
        let value = value.trim();
        // A primary ACCUMULATES; everything else takes the last definition.
        //
        // `make -p` on a recursive project concatenates the database of every
        // subdirectory, so one name can be defined several times meaning
        // different things. For a per-target variable that is harmless —
        // `xz_SOURCES` belongs to whichever directory declares `xz` and no
        // other — but a primary is declared once PER DIRECTORY, so xz emits
        // four `bin_PROGRAMS` lines (`xz`, `lzmainfo`, and the top level's
        // unexpanded `$(am__EXEEXT_1)`). Overwriting kept whichever came last
        // and silently dropped the rest: the conversion emitted `lzmainfo`,
        // omitted the project's namesake `xz` binary, and reported success.
        //
        // Not make's own semantics — make never sees these definitions
        // together, because each belongs to a different makefile.
        if is_primary(name) {
            match vars.entry(name.to_string()) {
                Entry::Occupied(mut slot) => {
                    let merged: &mut String = slot.get_mut();
                    if !merged.is_empty() && !value.is_empty() {
                        merged.push(' ');
                    }
                    merged.push_str(value);
                }
                Entry::Vacant(slot) => {
                    slot.insert(value.to_string());
                }
            }
            continue;
        }
        vars.insert(name.to_string(), value.to_string());
    }
    vars
}

/// Whether `name` is an automake primary — `bin_PROGRAMS`, `lib_LTLIBRARIES`.
///
/// Matched on the suffix alone, the same way [`declared_targets`] reads them,
/// so the two cannot disagree about what counts as a primary.
fn is_primary(name: &str) -> bool {
    name.rsplit_once('_')
        .is_some_and(|(_, primary)| matches!(primary, "PROGRAMS" | "LIBRARIES" | "LTLIBRARIES"))
}

/// Builds the `config_header` plan for an autoconf template, and the macros
/// it references that the shared catalog cannot resolve.
///
/// The catalog is the SAME one the CMake frontend maps `#cmakedefine` names
/// through — a `HAVE_UNISTD_H` probe is the same fact whichever build system
/// asked for it, and reusing the catalog is a large part of why Autotools was
/// the right second frontend rather than an excuse to build a parallel one.
///
/// Package metadata (`PACKAGE`, `VERSION`, ...) is resolved from make's
/// variable database rather than probed: those are values `configure`
/// substituted, not facts about the toolchain, so probing for them would be
/// both wrong and impossible.
pub(crate) fn plan_config_header(
    output: &str,
    template: &str,
    template_text: &str,
    vars: &HashMap<String, String>,
) -> (ConfigHeader, Vec<String>) {
    let mut probes = Vec::new();
    let mut values = Vec::new();
    let mut unmapped = Vec::new();

    for name in undef_names(template_text) {
        if let Some(label) = catalog_label(&name) {
            probes.push(label);
        } else if let Some(value) = vars.get(&name).filter(|v| !v.is_empty()) {
            // A value configure substituted — PACKAGE, VERSION and friends.
            //
            // The emptiness check is load-bearing, not defensive. `configure`
            // seeds make's database with EVERY macro it knows, most of them
            // empty, so a bare `vars.get` matches names it has no value for:
            // hello has `BITSIZEOF_PTRDIFF_T = ` in its database, and taking
            // that as a substitution emitted `"BITSIZEOF_PTRDIFF_T": """"` —
            // an unclosed string literal that would not parse. An empty
            // variable is the absence of a value, so the macro falls through
            // to the escalation below where it belongs.
            //
            // Stored unquoted: codegen renders a values entry as
            // `"NAME": "value"`, so quoting here would double it.
            values.push((name, value.clone()));
        } else {
            // Neither a catalog fact nor a substituted value. Escalated
            // rather than guessed at, exactly as the CMake frontend refuses
            // to match a project-prefixed alias to a lookalike catalog entry.
            unmapped.push(name);
        }
    }

    probes.sort_unstable();
    probes.dedup();
    values.sort_unstable();
    values.dedup();
    unmapped.sort_unstable();
    unmapped.dedup();

    (
        ConfigHeader {
            output: output.to_string(),
            template: template.to_string(),
            template_source: None,
            catalog_probes: probes,
            values,
        },
        unmapped,
    )
}

/// Every name an autoconf template declares with a bare `#undef`.
///
/// Line-anchored for the same reason the expander is: a mid-line `#undef` is
/// ordinary C undefining a macro, not a declaration to resolve.
fn undef_names(template_text: &str) -> Vec<String> {
    template_text
        .lines()
        .filter_map(|line| {
            let rest = line.strip_prefix('#')?.trim_start().strip_prefix("undef")?;
            let name = rest.trim();
            (!name.is_empty() && !name.contains(char::is_whitespace))
                .then(|| name.to_string())
        })
        .collect()
}

/// The config header a project declares with `AC_CONFIG_HEADERS`, as
/// (output, template) — `("config.h", "config.in")` for GNU hello.
///
/// Read from `config.status` rather than `configure.ac`, for the same reason
/// the rest of this frontend reads resolved output: `configure.ac` is the
/// input, and its macro arguments can be variables. `config.status` is what
/// `configure` actually decided, and it records BOTH sides:
///
/// ```text
/// config_headers=" config.h:config.in"
/// ```
///
/// The template is not always `<output>.in`. hello declares
/// `AC_CONFIG_HEADERS([config.h:config.in])` to keep the filename 8.3-safe,
/// so assuming the name would find nothing. Autoconf defaults the template to
/// `<output>.in` when only one side is given, which is handled here rather
/// than by the caller.
pub(crate) fn parse_config_headers(config_status: &str) -> Vec<(String, String)> {
    let Some(line) = config_status
        .lines()
        .find_map(|l| l.trim().strip_prefix("config_headers="))
    else {
        return Vec::new();
    };
    line.trim_matches(&['"', '\''][..])
        .split_whitespace()
        .map(|spec| match spec.split_once(':') {
            Some((output, template)) => (output.to_string(), template.to_string()),
            // Only the output named: autoconf's default template is
            // `<output>.in`.
            None => (spec.to_string(), format!("{spec}.in")),
        })
        .collect()
}

/// Recovers every target automake DECLARED, from the primaries.
///
/// This is the identity source. The command stream shows `-o greeter` — a
/// filename — while `bin_PROGRAMS = greeter` is the name automake actually
/// uses, and the `bin_` prefix additionally states where it installs.
/// Inferring identity from artifact paths instead breaks on a binary whose
/// name differs from its target's, on libtool's `.libs/libfoo.so.1.0.0`
/// versus `libfoo.la`, and on a non-empty `EXEEXT`.
pub(crate) fn declared_targets(vars: &HashMap<String, String>) -> Vec<DeclaredTarget> {
    let mut targets = Vec::new();
    for (var, value) in vars {
        let Some((destination, primary)) = var.rsplit_once('_') else {
            continue;
        };
        if !matches!(primary, "PROGRAMS" | "LIBRARIES" | "LTLIBRARIES") {
            continue;
        }
        // `dist_`, `nodist_` and `nobase_` are modifiers automake allows in
        // front of the destination; the destination is the last segment.
        let destination = destination.rsplit('_').next().unwrap_or(destination);
        for name in value.split_whitespace() {
            // $(EXEEXT) is empty on Linux and `.exe` elsewhere; the database
            // provides it, so it is expanded rather than assumed.
            let exeext = vars.get("EXEEXT").map(String::as_str).unwrap_or("");
            let name = name.replace("$(EXEEXT)", exeext);
            if name.is_empty() {
                continue;
            }
            // An unexpanded reference, not a target. A recursive project's
            // top-level `bin_PROGRAMS` is often a list of `$(am__EXEEXT_N)`
            // internals; the real names come from the subdirectory
            // definitions, which parse_variables merges in alongside these.
            // Taking one as a name produces a target automake never declared,
            // matched against no build command, escalated as unbuilt.
            if name.contains("$(") {
                continue;
            }
            targets.push(DeclaredTarget {
                name,
                destination: destination.to_string(),
                primary: primary.to_string(),
            });
        }
    }
    targets.sort_by(|a, b| a.name.cmp(&b.name));
    targets.dedup();
    targets
}

/// The variable prefix automake derives from a target name.
///
/// automake canonicalises by replacing every character that is not
/// alphanumeric or `_` with `_`, so `libshout.la` owns `libshout_la_SOURCES`.
/// Without this the per-target variables cannot be found at all.
pub(crate) fn canonical_name(target_name: &str) -> String {
    target_name
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

/// Splits `make -n` output into the commands that actually build something.
///
/// Deliberately conservative about what it keeps. The stream is interleaved
/// with shell bookkeeping automake emits around every compile — `depbase=...`
/// assignments, `mv -f`, `rm -f`, `test -z || mkdir` — and with `make`'s own
/// directory chatter. Recognising only the handful of programs that produce
/// build outputs means an unrecognised line is IGNORED rather than
/// misinterpreted, which is the safe direction: a missed command shows up as a
/// target with no sources, while a misparsed one would silently produce a
/// wrong rule.
pub(crate) fn parse_commands(stdout: &str, build_dir: &Path) -> Vec<BuildCommand> {
    let mut commands = Vec::new();
    // make announces each descent, and the announcements nest — `make[2]`
    // inside `make[1]`. Tracked as a stack rather than a single "current"
    // value so a Leaving line restores the enclosing directory rather than
    // guessing at the root.
    let mut dirs: Vec<PathBuf> = vec![build_dir.to_path_buf()];
    for line in stdout.lines() {
        if let Some(dir) = entering_directory(line) {
            dirs.push(dir);
            continue;
        }
        if leaving_directory(line) {
            // Never pop the base: an unbalanced Leaving (a sub-make whose
            // Entering was filtered out, say) must not leave the stack empty.
            if dirs.len() > 1 {
                dirs.pop();
            }
            continue;
        }
        let current = dirs.last().expect("the base directory is never popped");
        // A `&&`/`;`-joined line can carry several commands; automake writes
        // `depbase=...; gcc ...` as one line.
        for piece in line.split("&&").flat_map(|p| p.split(';')) {
            let piece = piece.trim().trim_end_matches('\\').trim();
            if piece.is_empty() {
                continue;
            }
            let mut tokens = tokenize(piece);
            if tokens.is_empty() {
                continue;
            }
            // `/bin/bash ./libtool --tag=CC --mode=link gcc ...` — the real
            // compiler is several tokens in. Strip the wrappers AND libtool's
            // own flags, which sit between it and the command it wraps; a
            // stripper that stopped at the first non-wrapper would take
            // `--tag=CC` for the program and silently drop every libtool
            // target, which is most of an autotools library build.
            while tokens
                .first()
                .is_some_and(|t| is_shell_wrapper(t) || is_libtool_flag(t))
            {
                tokens.remove(0);
            }
            let program = tokens.remove(0);
            let program = Path::new(&program)
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or(program);
            if !is_build_program(&program) {
                continue;
            }
            commands.push(BuildCommand {
                program,
                args: tokens,
                dir: current.clone(),
            });
        }
    }
    commands
}

/// Whether a token is one of libtool's own options rather than part of the
/// command it wraps. Only the ones that appear BEFORE the wrapped program —
/// `--mode=link` and friends — since everything after belongs to the compiler.
fn is_libtool_flag(token: &str) -> bool {
    token.starts_with("--tag=")
        || token.starts_with("--mode=")
        || matches!(token, "--silent" | "--quiet" | "--verbose")
}

/// The directory a `make[N]: Entering directory '...'` line announces.
fn entering_directory(line: &str) -> Option<PathBuf> {
    let rest = line.split_once("Entering directory ")?.1;
    Some(PathBuf::from(rest.trim().trim_matches(&['\'', '`'][..])))
}

/// Whether a line announces make leaving a directory.
fn leaving_directory(line: &str) -> bool {
    line.contains("Leaving directory ")
}

/// Whether a token is a shell the real command is being run through.
fn is_shell_wrapper(token: &str) -> bool {
    matches!(
        Path::new(token).file_name().and_then(|n| n.to_str()),
        Some("bash" | "sh" | "libtool")
    )
}

/// Whether a program produces a build output worth modelling.
///
/// `ranlib` is deliberately absent: it indexes an archive `ar` already
/// created, so treating it as a target would double-count the library.
fn is_build_program(program: &str) -> bool {
    matches!(
        program,
        "gcc" | "g++" | "cc" | "c++" | "clang" | "clang++" | "ar"
    )
}

/// Splits a command into tokens, honouring quotes but not expanding anything.
///
/// Not a shell parser: `make -n` output is already expanded, so the only job
/// is to keep a quoted `-DPACKAGE_STRING="greeter 1.0"` in one piece rather
/// than splitting it on the space.
fn tokenize(line: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut quote: Option<char> = None;
    let mut escaped = false;

    for c in line.chars() {
        if escaped {
            current.push(c);
            escaped = false;
            continue;
        }
        match c {
            '\\' => escaped = true,
            '"' | '\'' if quote.is_none() => quote = Some(c),
            c if Some(c) == quote => quote = None,
            c if c.is_whitespace() && quote.is_none() => {
                if !current.is_empty() {
                    tokens.push(std::mem::take(&mut current));
                }
            }
            c => current.push(c),
        }
    }
    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

/// Builds the graph, joining automake's DECLARATIONS to the build's own
/// COMMAND STREAM.
///
/// Each source answers what the other cannot, which is why both are read:
///
/// - the variable database gives target IDENTITY — the name automake uses,
///   the install destination, and which primary declared it. None of that is
///   in the command stream, which shows only `-o greeter`.
/// - the command stream gives what was actually BUILT — the resolved `-I` and
///   `-D` per compile, and which objects really went into which artifact.
///   None of that is in the database, which shows declarations before
///   automake's own conditionals and rules have had their say.
///
/// The two are joined on the artifact each target produces, which both name.
/// This mirrors `cmake_api`, where the File API is primary and the configure
/// trace is a deliberate, documented second source.
pub(crate) fn to_graph(
    commands: &[BuildCommand],
    declared: &[DeclaredTarget],
    vars: &HashMap<String, String>,
    project_name: &str,
    module_root: &Path,
    build_root: &Path,
) -> (BuildGraph, Vec<crate::needs_attention::NeedsAttention>) {
    // Resolve a path reported by a command against the directory that command
    // ran in, then express it relative to the module root. Returns None when
    // it escapes the module, which a Bazel label cannot express.
    // Two roots, because an out-of-tree build reports paths against both. A
    // compile in <build>/src/lzmainfo carries `-I../..` (the build root) AND
    // `-I<source>/src/common` (the source tree) on the same line, and both
    // name real directories. Resolving against the command's directory then
    // trying each root is what makes them comparable; the build-root form
    // maps onto the source tree because the two trees mirror each other.
    let rebase = |path: &str, dir: &Path| -> Option<String> {
        let absolute = normalize_lexically(&dir.join(path));
        if let Ok(rel) = absolute.strip_prefix(module_root) {
            return Some(rel.to_string_lossy().into_owned());
        }
        absolute
            .strip_prefix(build_root)
            .ok()
            .map(|rel| rel.to_string_lossy().into_owned())
    };
    // object path -> the source it was compiled from, and the flags it carried.
    let mut source_of: HashMap<String, (String, PathBuf)> = HashMap::new();
    let mut flags_of: HashMap<String, (Vec<String>, Vec<String>)> = HashMap::new();
    for cmd in commands.iter().filter(|c| c.program != "ar") {
        let Some(output) = flag_value(&cmd.args, "-o") else {
            continue;
        };
        if !cmd.args.iter().any(|a| a == "-c") {
            continue;
        }
        if let Some(source) = compiled_source(&cmd.args) {
            source_of.insert(output.clone(), (source, cmd.dir.clone()));
            flags_of.insert(output, (includes_of(&cmd.args), defines_of(&cmd.args)));
        }
    }

    // artifact basename -> the link/archive command that produced it, so a
    // declared target can find the step that built it.
    let mut built: HashMap<String, &BuildCommand> = HashMap::new();
    for cmd in commands {
        if let Some(artifact) = produced_artifact(cmd) {
            built.insert(basename(&artifact), cmd);
        }
    }

    // Targets automake declared but the build never produced. `check_PROGRAMS`
    // are the live case: `make` does not build them (that is `make check`), so
    // no link command exists and nothing says which directory their sources
    // are relative to. Skipping them is honest — a target with sources
    // resolved against a guessed directory is worse than an absent one, and
    // the guess fails loudly on copy, which is how this was found. Recorded
    // for the escalation they deserve.
    let mut unbuilt: Vec<String> = Vec::new();
    let mut targets = Vec::new();
    // External libraries any target links but the project does not build.
    // Gathered across all targets so the caller can escalate them once.
    let mut external_links: Vec<String> = Vec::new();
    // Sources a target compiles that lie outside the module, paired with the
    // target that lost them: a dropped source is a link failure, and the
    // escalation has to say which rule is now incomplete. Flattening these
    // into one module-wide list would throw away exactly that.
    let mut outside_module: Vec<(String, Vec<String>)> = Vec::new();
    for decl in declared {
        let canon = canonical_name(&decl.name);
        if built.get(&basename(&decl.name)).is_none() {
            unbuilt.push(decl.name.clone());
            continue;
        }

        // Sources come from the DECLARATION, not from the link inputs: a
        // target's _SOURCES is what automake was told, while the link line
        // shows objects, which have to be mapped back. Headers appear in
        // _SOURCES too (automake accepts them so they reach the tarball), so
        // they are split out rather than compiled.
        let declared_sources = vars
            .get(&format!("{canon}_SOURCES"))
            .map(|v| v.split_whitespace().map(str::to_string).collect())
            .unwrap_or_else(Vec::new);
        let (headers, declared_sources): (Vec<String>, Vec<String>) = declared_sources
            .into_iter()
            .partition(|s| !is_source_file(s));

        // A target's _SOURCES are relative to the Makefile.am that DECLARED
        // them — fixture 002 declares `tool_SOURCES = main.c ../common/util.c`
        // in app/, so `../common/util.c` means nothing until resolved against
        // app/. The link command runs in that same directory, but in the BUILD
        // tree; for an out-of-tree build the sources live under the SOURCE
        // tree, so the build-relative part of that directory is what carries
        // over.
        let decl_dir = built
            .get(&basename(&decl.name))
            .and_then(|cmd| cmd.dir.strip_prefix(build_root).ok())
            .map(|rel| module_root.join(rel))
            .unwrap_or_else(|| module_root.to_path_buf());
        let mut sources: Vec<String> = declared_sources
            .iter()
            .filter_map(|src| rebase(src, &decl_dir))
            .collect();
        let mut escaped: Vec<String> = declared_sources
            .iter()
            .filter(|src| rebase(src, &decl_dir).is_none())
            .map(|src| normalize_lexically(&decl_dir.join(src)).to_string_lossy().into_owned())
            .collect();

        // Flags come from the COMMAND STREAM, via the objects this target's
        // sources compiled to — the database's *_CPPFLAGS are pre-expansion
        // and miss what configure and AM_CPPFLAGS contributed.
        let mut includes = Vec::new();
        let mut local_defines = Vec::new();
        let mut needs_root_include = false;
        for (object, (source, dir)) in &source_of {
            // Compare in module-relative terms: the object map keys sources as
            // the command reported them, which is per-directory.
            if !rebase(source, dir).is_some_and(|s| sources.contains(&s)) {
                continue;
            }
            if let Some((inc, def)) = flags_of.get(object) {
                // An include dir is likewise relative to the compiling
                // directory. One that resolves TO the module root cannot be
                // an `includes` entry (Bazel rejects "."), so it is recorded
                // the way the CMake frontend records it and codegen stages
                // headers into _include/.
                for i in inc {
                    match rebase(i, dir) {
                        Some(rel) if rel.is_empty() => needs_root_include = true,
                        Some(rel) => includes.push(rel),
                        // An include path outside the module — a system or
                        // toolchain directory. Dropped rather than emitted:
                        // an absolute build-machine path in `includes` is
                        // accepted by Bazel silently and makes the module
                        // build only where it was converted.
                        None => {}
                    }
                }
                local_defines.extend(def.iter().cloned());
            }
        }

        let link = built.get(&basename(&decl.name));
        // Relative to the BUILD dir, not the module: this is where the real
        // built binary sits, and copy_ground_truth_artifacts reads it from
        // there. The link command reports `-o tool` from inside app/, so
        // without rebasing the artifact records as bare `tool` and the copy
        // fails on a path that does not exist.
        let artifact = link
            .and_then(|cmd| {
                let out = produced_artifact(cmd)?;
                let absolute = normalize_lexically(&cmd.dir.join(&out));
                absolute
                    .strip_prefix(build_root)
                    .ok()
                    .map(|rel| rel.to_string_lossy().into_owned())
            })
            .unwrap_or_else(|| decl.name.clone());

        // Dependencies come from the COMMAND STREAM, not from _LDADD.
        //
        // The database reports LDADD unexpanded — GNU hello's is literally
        //   hello_LDADD = $(LIBINTL) $(top_builddir)/lib/lib$(PACKAGE).a
        // so matching its tokens against declared names finds nothing and
        // drops every edge in silence. That is the same lesson cmake_api
        // records about CMakeLists.txt: the declaration is the unresolved
        // half. The link line carries the resolved `./lib/libhello.a`.
        let mut dependencies: Vec<String> = Vec::new();
        let mut unresolved: Vec<String> = Vec::new();
        for input in link.map(|cmd| cmd.args.as_slice()).unwrap_or(&[]) {
            if !is_library(input) {
                continue;
            }
            match declared.iter().find(|d| basename(&d.name) == basename(input)) {
                Some(dep) if dep.name != decl.name => dependencies.push(target_label(&dep.name)),
                Some(_) => {}
                // A library the project links but does not build — $(LIBINTL)
                // resolves to a system libintl, for instance. Collected rather
                // than dropped: it is an input the generated module cannot
                // satisfy, which is an escalation, not a silent omission.
                None => unresolved.push(input.clone()),
            }
        }
        external_links.extend(unresolved);

        sources.sort_unstable();
        sources.dedup();
        dependencies.sort_unstable();
        dependencies.dedup();
        includes.sort_unstable();
        includes.dedup();
        local_defines.sort_unstable();
        local_defines.dedup();

        targets.push(Target {
            name: target_label(&decl.name),
            kind: match decl.primary.as_str() {
                "PROGRAMS" => TargetKind::Executable,
                _ => TargetKind::Library,
            },
            // From the PRIMARY, not from a filename: LTLIBRARIES is libtool's
            // form and builds a shared library, LIBRARIES is a plain archive.
            is_shared: decl.primary == "LTLIBRARIES",
            sources,
            // `include_HEADERS` names the project's public headers, the same
            // statement CMake makes with install(FILES ... DESTINATION
            // include). A header in _SOURCES that is not installed stays
            // private.
            public_headers: headers
                .iter()
                .filter(|h| public_headers(vars).contains(*h))
                .cloned()
                .collect(),
            dependencies,
            includes,
            local_defines,
            needs_root_include,
            artifacts: vec![artifact],
            ..Default::default()
        });
        escaped.sort_unstable();
        escaped.dedup();
        if !escaped.is_empty() {
            outside_module.push((decl.name.clone(), escaped));
        }
    }

    targets.sort_by(|a, b| a.name.cmp(&b.name));
    external_links.sort_unstable();
    external_links.dedup();
    outside_module.sort_by(|a, b| a.0.cmp(&b.0));
    unbuilt.sort_unstable();
    unbuilt.dedup();

    // A source that escaped the module is the one drop that fails silently.
    // The target still renders, still links, and reports an undefined symbol
    // several steps from the cause; the other two announce themselves (a
    // missing check_PROGRAMS is absent, a system library fails to resolve).
    // Escalated per target because the resolution is per target: which rule is
    // incomplete is the first thing the agent needs.
    let needs_attention = outside_module
        .iter()
        .map(|(target, sources)| sources_outside_deliverable_needs_attention(target, sources))
        .collect();

    // Not yet escalated — see bzl-yjn.5. Recorded here so the information is
    // recovered rather than discarded, and so the escalation, when it lands,
    // has something to report.
    let _ = (&external_links, &unbuilt);

    (
        BuildGraph {
            module: ModuleInfo {
                name: project_name.to_string(),
                version: vars.get("VERSION").cloned(),
            },
            targets,
            tests: Vec::new(),
            config_headers: Vec::new(),
        },
        needs_attention,
    )
}

/// Every header the project installs, from any `*_HEADERS` primary.
fn public_headers(vars: &HashMap<String, String>) -> Vec<String> {
    vars.iter()
        .filter(|(k, _)| {
            k.ends_with("_HEADERS") && !k.starts_with("noinst") && !k.starts_with("EXTRA")
        })
        .flat_map(|(_, v)| v.split_whitespace().map(str::to_string))
        .collect()
}

/// The Bazel target name for an automake target name.
///
/// Sanitises rather than prettifies: automake already gave us the name, so the
/// only job is to make it a legal Bazel label. An earlier version stripped the
/// `lib` prefix and the suffix, so `libgreet.a` read as `greet` — which is
/// nicer until a project names its library after its program. GNU hello does
/// exactly that (`bin_PROGRAMS = hello`, `noinst_LIBRARIES = lib/libhello.a`),
/// and both collapsed to `hello`: two rules with one name, and a module that
/// cannot load. That is the COMMON shape, not an edge case, and prettiness is
/// not worth a name clash.
///
/// The directory is kept for the same reason — `lib/libhello.a` and
/// `src/libhello.a` are different targets in a project with SUBDIRS.
fn target_label(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' || c == '-' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// The artifact a link or archive command produces, or `None` for a compile.
fn produced_artifact(cmd: &BuildCommand) -> Option<String> {
    if cmd.program == "ar" {
        let mut rest = cmd.args.iter().filter(|a| !a.starts_with('-'));
        let _mode = rest.next();
        return rest.next().cloned();
    }
    if cmd.args.iter().any(|a| a == "-c") {
        return None;
    }
    flag_value(&cmd.args, "-o")
}

fn basename(path: &str) -> String {
    Path::new(path)
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.to_string())
}

/// The value following `flag`, e.g. `-o foo` -> `foo`.
fn flag_value(args: &[String], flag: &str) -> Option<String> {
    args.iter()
        .position(|a| a == flag)
        .and_then(|i| args.get(i + 1))
        .cloned()
}

/// `-I` directories, with the flag stripped and `.`-relative paths kept.
fn includes_of(args: &[String]) -> Vec<String> {
    args.iter()
        .filter_map(|a| a.strip_prefix("-I"))
        .filter(|d| !d.is_empty())
        .map(str::to_string)
        .collect()
}

/// `-D` definitions, with the flag stripped.
///
/// autoconf passes a large block of `-DPACKAGE_*` and `-DHAVE_*` on every
/// compile; those are the config-header facts, kept as-is here and left for a
/// later pass to route through `cc_config` the way `configure_file` does.
fn defines_of(args: &[String]) -> Vec<String> {
    args.iter()
        .filter_map(|a| a.strip_prefix("-D"))
        .filter(|d| !d.is_empty())
        .map(str::to_string)
        .collect()
}

/// The source file a compile command names, seeing through automake's VPATH
/// guard.
///
/// A subdir-objects compile does not name the source plainly. It emits
///
///   `test -f 'lzmainfo.c' || echo '<srcdir>/src/lzmainfo/'`lzmainfo.c
///
/// so the compiler finds the file whether the build is in-tree or out-of-tree.
/// Tokenised, that is SEVERAL arguments, two of which look like sources — the
/// bare `lzmainfo.c` inside the test is a decoy. The LAST argument is the real
/// one; the guard is never evaluated, because the echoed directory is already
/// the path wanted and running `test -f` would make the answer depend on the
/// filesystem the frontend happens to run against. Full account, including how
/// it surfaces, in
/// docs/lore/automake-wraps-sources-in-a-vpath-guard.md.
fn compiled_source(args: &[String]) -> Option<String> {
    // The LAST argument, always: everything before it is either flags or the
    // guard's own words. Tokenising the guard leaves the echoed directory
    // glued to the filename by the closing backtick —
    // `/src/src/lzmainfo/`lzmainfo.c` — so splitting on that backtick and
    // rejoining recovers the real path, while a plain source has no backtick
    // and passes through untouched.
    let last = args.last()?;
    let full = match last.split_once('`') {
        Some((dir, name)) => format!("{dir}{name}"),
        None => last.clone(),
    };
    is_source_file(&full).then_some(full)
}

fn is_source_file(path: &str) -> bool {
    matches!(
        Path::new(path).extension().and_then(|e| e.to_str()),
        Some("c" | "cc" | "cpp" | "cxx" | "m" | "mm" | "s" | "S")
    )
}

fn is_library(path: &str) -> bool {
    path.ends_with(".a") || path.ends_with(".la") || path.contains(".so")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen;

    /// A real `make -n` capture from fixture 001, trimmed of the autoconf
    /// -DPACKAGE_* block for readability. Frozen evidence: this is what
    /// automake actually emits, so the parser can be wrong against it.
    /// A real `make -n -B` capture from fixture 001, verbatim.
    ///
    /// Frozen evidence, so it is the build system's output and not ours:
    /// the `-DPACKAGE_*` block, the single `-I.`, the `depbase=` shell
    /// bookkeeping and libtool's `--tag=CC` are all what automake really
    /// emits. An earlier hand-written version carried an `-Isrc` automake
    /// never produces, and an assertion about per-target include
    /// attribution was passing against that invented flag.
    ///
    /// This is the IN-TREE shape. An out-of-tree build reports the
    /// compiled source as an absolute path — not covered here, and the
    /// reason fixture conversion stays the tier that can contradict us.
    const STREAM: &str = r#"
depbase=`echo src/main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"greeter\" -DPACKAGE_TARNAME=\"greeter\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"greeter\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"greeter\" -DVERSION=\"1.0\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.     -g -O2 -MT src/main.o -MD -MP -MF $depbase.Tpo -c -o src/main.o src/main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/greet.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"greeter\" -DPACKAGE_TARNAME=\"greeter\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"greeter\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"greeter\" -DVERSION=\"1.0\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.     -g -O2 -MT src/greet.o -MD -MP -MF $depbase.Tpo -c -o src/greet.o src/greet.c &&\
mv -f $depbase.Tpo $depbase.Po
rm -f libgreet.a
ar cru libgreet.a src/greet.o 
ranlib libgreet.a
depbase=`echo src/shout.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"greeter\" -DPACKAGE_TARNAME=\"greeter\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"greeter\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"greeter\" -DVERSION=\"1.0\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.     -g -O2 -MT src/shout.lo -MD -MP -MF $depbase.Tpo -c -o src/shout.lo src/shout.c &&\
mv -f $depbase.Tpo $depbase.Plo
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o libshout.la -rpath /usr/local/lib src/shout.lo  
rm -f greeter
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o greeter src/main.o libgreet.a libshout.la 
"#;

    /// A real `make -p -n` capture from fixture 001, trimmed to the lines
    /// that carry declarations. Frozen evidence: this is what automake
    /// actually puts in make's database.
    const DATABASE: &str = "\
EXEEXT = \n\
VERSION = 1.0\n\
bin_PROGRAMS = greeter$(EXEEXT)\n\
noinst_LIBRARIES = libgreet.a\n\
lib_LTLIBRARIES = libshout.la\n\
include_HEADERS = src/greet.h\n\
greeter_SOURCES = src/main.c\n\
greeter_LDADD = libgreet.a libshout.la\n\
libgreet_a_SOURCES = src/greet.c src/greet.h\n\
libshout_la_SOURCES = src/shout.c\n\
";

    /// Both frozen captures are from a build rooted here, so paths in them
    /// resolve against it. An in-tree build, where the source and build roots
    /// coincide, is the simplest case that still exercises the rebasing.
    const ROOT: &str = "/src";

    fn graph_from_captures() -> BuildGraph {
        let vars = parse_variables(DATABASE);
        let declared = declared_targets(&vars);
        graph_only(to_graph(
            &parse_commands(STREAM, Path::new(ROOT)),
            &declared,
            &vars,
            "greeter",
            Path::new(ROOT),
            Path::new(ROOT),
        ))
    }

    /// Drops the escalations `to_graph` returns alongside the graph.
    ///
    /// Only for tests asserting on graph shape. A test about what the frontend
    /// ESCALATES must read the second element instead of reaching for this.
    fn graph_only(result: (BuildGraph, Vec<crate::needs_attention::NeedsAttention>)) -> BuildGraph {
        result.0
    }

    // bzl-yjn.7: recursive make runs each subdirectory's commands from that
    // subdirectory, so a path in the stream is relative to IT, not to the
    // build root. xz compiles ../common/tuklib_*.c from src/xz; fixture 002
    // reproduces it with ../common/util.c from app/. Emitted verbatim, that
    // is a label reaching above its own module, which codegen refuses.
    #[test]
    fn a_commands_paths_resolve_against_the_directory_it_ran_in() {
        const STREAM: &str = "\
make[1]: Entering directory '/src/app'\n\
gcc -I. -I../common -c -o main.o main.c\n\
gcc -c -o util.o ../common/util.c\n\
gcc -o tool main.o util.o\n\
make[1]: Leaving directory '/src/app'\n\
";
        let commands = parse_commands(STREAM, Path::new("/src"));
        assert!(
            commands.iter().all(|c| c.dir == Path::new("/src/app")),
            "every command between Entering and Leaving runs in that \
             directory: {commands:#?}"
        );

        let vars = parse_variables("bin_PROGRAMS = tool\ntool_SOURCES = main.c ../common/util.c\n");
        let declared = declared_targets(&vars);
        let graph = graph_only(to_graph(
            &commands,
            &declared,
            &vars,
            "sibling",
            Path::new("/src"),
            Path::new("/src"),
        ));
        let tool = &graph.targets[0];
        assert_eq!(
            tool.sources,
            vec!["app/main.c", "common/util.c"],
            "the sibling source resolves to its module-relative path, not to \
             the literal ../common/util.c the command reported:\n{tool:#?}"
        );
        assert_eq!(
            tool.includes,
            vec!["app", "common"],
            "-I. and -I../common both resolve against app/, giving app and \
             common — neither is the module root here, so nothing is \
             dropped:\n{tool:#?}"
        );
        assert!(
            !tool.needs_root_include,
            "no include dir resolves TO the module root in this stream: \
             {tool:#?}"
        );
        assert_eq!(
            tool.artifacts,
            vec!["app/tool"],
            "and the artifact is where the build actually put it — `-o tool` \
             from inside app/ is app/tool, not a bare tool that no copy can \
             find"
        );
    }

    // Both directions for the outside-module escalation, because a gate only
    // ever seen firing is indistinguishable from one wired to nothing. The
    // negative is the sibling case above: `../common/util.c` looks like it
    // escapes and does not, so a check that merely spots `..` would fire on it.
    #[test]
    fn a_source_that_escapes_the_module_is_escalated_not_dropped() {
        const STREAM: &str = "\
make[1]: Entering directory '/src/app'\n\
gcc -c -o main.o main.c\n\
gcc -c -o evil.o ../../outside/evil.c\n\
gcc -o tool main.o evil.o\n\
make[1]: Leaving directory '/src/app'\n\
";
        let vars =
            parse_variables("bin_PROGRAMS = tool\ntool_SOURCES = main.c ../../outside/evil.c\n");
        let (graph, escalations) = to_graph(
            &parse_commands(STREAM, Path::new("/src")),
            &declared_targets(&vars),
            &vars,
            "escaper",
            Path::new("/src"),
            Path::new("/src"),
        );

        let tool = &graph.targets[0];
        assert_eq!(
            tool.sources,
            vec!["app/main.c"],
            "the escaping source cannot be a label and is left out:\n{tool:#?}"
        );
        assert_eq!(
            escalations.len(),
            1,
            "leaving it out silently makes the target fail to link with an \
             undefined symbol several steps from the cause; got: {escalations:#?}"
        );
        assert!(
            escalations[0].gap.contains("outside/evil.c") && escalations[0].title.contains("tool"),
            "the escalation must name the file AND the target now missing it, \
             because the resolution is per target; got:\n{:#?}",
            escalations[0]
        );
    }

    #[test]
    fn a_sibling_source_inside_the_module_is_not_escalated() {
        const STREAM: &str = "\
make[1]: Entering directory '/src/app'\n\
gcc -c -o main.o main.c\n\
gcc -c -o util.o ../common/util.c\n\
gcc -o tool main.o util.o\n\
make[1]: Leaving directory '/src/app'\n\
";
        let vars = parse_variables("bin_PROGRAMS = tool\ntool_SOURCES = main.c ../common/util.c\n");
        let (_, escalations) = to_graph(
            &parse_commands(STREAM, Path::new("/src")),
            &declared_targets(&vars),
            &vars,
            "sibling",
            Path::new("/src"),
            Path::new("/src"),
        );
        assert!(
            escalations.is_empty(),
            "`../common/util.c` leaves app/ but stays inside the module, so it \
             resolves to common/util.c and nothing is missing; got: \
             {escalations:#?}"
        );
    }

    // automake's subdir-objects compiles do not name the source plainly; they
    // wrap it in a VPATH guard that tokenises into several arguments, two of
    // which look like sources. Taking the last source-LOOKING token picks the
    // bare filename inside the `test -f`, so the compile's flags attach to no
    // target and the rule renders with empty `includes` — several steps from
    // the cause. xz is full of these.
    #[test]
    fn compiled_source_sees_through_automakes_vpath_guard() {
        // As tokenize() actually yields it: the quotes are consumed, so the
        // echoed directory and the filename arrive as ONE token joined by the
        // closing backtick.
        let args: Vec<String> = [
            "-c",
            "-o",
            "lzmainfo-lzmainfo.o",
            "`test",
            "-f",
            "lzmainfo.c",
            "||",
            "echo",
            "/src/src/lzmainfo/`lzmainfo.c",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        assert_eq!(
            compiled_source(&args).as_deref(),
            Some("/src/src/lzmainfo/lzmainfo.c"),
            "the echoed directory names where the file really is; the bare \
             lzmainfo.c inside the test is a decoy"
        );

        // An unguarded compile still works.
        let plain: Vec<String> = "-c -o main.o main.c"
            .split_whitespace()
            .map(str::to_string)
            .collect();
        assert_eq!(compiled_source(&plain).as_deref(), Some("main.c"));
    }

    // AC_CONFIG_HEADERS names BOTH sides, and the template is not always
    // `<output>.in` — GNU hello declares config.h:config.in to keep the name
    // 8.3-safe, so assuming would find nothing.
    #[test]
    fn parse_config_headers_reads_both_sides_of_the_declaration() {
        assert_eq!(
            parse_config_headers("config_headers=\" config.h:config.in\"\n"),
            vec![("config.h".to_string(), "config.in".to_string())]
        );
        // Only the output named: autoconf defaults the template to <output>.in.
        assert_eq!(
            parse_config_headers("config_headers=\"config.h\"\n"),
            vec![("config.h".to_string(), "config.h.in".to_string())]
        );
        // A project declaring none — fixture 001 — must yield none rather
        // than a default that does not exist.
        assert!(parse_config_headers("other=1\n").is_empty());
    }

    // `configure` seeds make's database with EVERY macro it knows, most of
    // them EMPTY. Treating an empty variable as a substituted value emitted
    //     "BITSIZEOF_PTRDIFF_T": """"
    // — an unclosed string literal, so the generated module would not parse.
    // The macro belongs in the escalation instead.
    #[test]
    fn an_empty_make_variable_is_not_a_substituted_value() {
        let vars: HashMap<String, String> = [
            ("PACKAGE".to_string(), "hello".to_string()),
            ("BITSIZEOF_PTRDIFF_T".to_string(), String::new()),
        ]
        .into_iter()
        .collect();
        let (header, unmapped) = plan_config_header(
            "config.h",
            "config.in",
            "#undef PACKAGE\n#undef BITSIZEOF_PTRDIFF_T\n#undef HAVE_UNISTD_H\n",
            &vars,
        );

        assert_eq!(
            header.values,
            vec![("PACKAGE".to_string(), "hello".to_string())],
            "only a real substitution is a value, and it is stored UNQUOTED — \
             codegen renders `\"NAME\": \"value\"`, so quoting here doubles it"
        );
        assert_eq!(
            header.catalog_probes,
            vec!["@cc_config//catalog:have_unistd_h"],
            "a catalog fact is probed, not substituted"
        );
        assert_eq!(
            unmapped,
            vec!["BITSIZEOF_PTRDIFF_T"],
            "an empty variable is the ABSENCE of a value, so the macro is \
             escalated rather than emitted as an empty string"
        );
    }

    // GNU hello's database reports LDADD UNEXPANDED:
    //   hello_LDADD = $(LIBINTL) $(top_builddir)/lib/lib$(PACKAGE).a
    // Matching those tokens against declared names finds nothing, so taking
    // edges from the declaration dropped every dependency in silence. The
    // link line carries the resolved path, which is why edges come from the
    // command stream instead.
    #[test]
    fn dependencies_come_from_the_link_line_not_the_unexpanded_declaration() {
        const DB: &str = "\
bin_PROGRAMS = hello\n\
noinst_LIBRARIES = lib/libhello.a\n\
hello_SOURCES = src/hello.c\n\
hello_LDADD = $(LIBINTL) $(top_builddir)/lib/lib$(PACKAGE).a\n\
";
        const STREAM_WITH_RESOLVED_LINK: &str = "\
gcc -I. -c -o src/hello.o src/hello.c\n\
ar cru lib/libhello.a lib/basename.o\n\
gcc -g -O2 -o hello src/hello.o ./lib/libhello.a\n\
";
        let vars = parse_variables(DB);
        let declared = declared_targets(&vars);
        let graph = graph_only(to_graph(
            &parse_commands(STREAM_WITH_RESOLVED_LINK, Path::new(ROOT)),
            &declared,
            &vars,
            "hello",
            Path::new(ROOT),
            Path::new(ROOT),
        ));

        let hello = graph
            .targets
            .iter()
            .find(|t| t.name == "hello")
            .expect("the program must render");
        assert_eq!(
            hello.dependencies,
            vec!["lib_libhello.a"],
            "the edge is in the link line as ./lib/libhello.a; the declaration \
             only has $(top_builddir)/lib/lib$(PACKAGE).a, which resolves to \
             nothing here:\n{hello:#?}"
        );
    }

    // GNU hello: bin_PROGRAMS = hello and noinst_LIBRARIES = lib/libhello.a.
    // Stripping `lib` and the suffix rendered BOTH as `hello`, giving a module
    // with two rules of one name that cannot load. A project naming its
    // library after its program is the common shape, so this is pinned
    // directly rather than left to the fixture, which happens not to collide.
    #[test]
    fn target_label_does_not_collapse_a_program_and_its_library() {
        assert_ne!(
            target_label("hello"),
            target_label("lib/libhello.a"),
            "a program and its own library must stay distinct targets"
        );
        // Sanitised for Bazel, not shortened: the name automake gave is kept.
        assert_eq!(target_label("lib/libhello.a"), "lib_libhello.a");
        assert_eq!(target_label("hello"), "hello");
        // The directory is part of the identity — two SUBDIRS can each
        // declare a libhello.a.
        assert_ne!(
            target_label("lib/libhello.a"),
            target_label("src/libhello.a")
        );
    }

    // automake canonicalises a target name into its variable prefix by
    // replacing every non-alphanumeric character. Without this,
    // `libshout.la`'s sources cannot be found at all.
    #[test]
    fn canonical_name_matches_automakes_variable_naming() {
        assert_eq!(canonical_name("greeter"), "greeter");
        assert_eq!(canonical_name("libshout.la"), "libshout_la");
        assert_eq!(canonical_name("libgreet.a"), "libgreet_a");
        assert_eq!(canonical_name("my-tool"), "my_tool");
    }

    // Identity comes from the primaries, not from artifact paths. The
    // destination prefix is carried because it is where the public/private
    // signal lives — noinst_ means built but never installed.
    #[test]
    fn declared_targets_recovers_names_destinations_and_primaries() {
        let declared = declared_targets(&parse_variables(DATABASE));
        assert_eq!(
            declared,
            vec![
                DeclaredTarget {
                    name: "greeter".to_string(),
                    destination: "bin".to_string(),
                    primary: "PROGRAMS".to_string(),
                },
                DeclaredTarget {
                    name: "libgreet.a".to_string(),
                    destination: "noinst".to_string(),
                    primary: "LIBRARIES".to_string(),
                },
                DeclaredTarget {
                    name: "libshout.la".to_string(),
                    destination: "lib".to_string(),
                    primary: "LTLIBRARIES".to_string(),
                },
            ],
            "$(EXEEXT) must be expanded from the database, not assumed empty"
        );
    }

    // Verbatim from a real `make -p -n` on xz 5.4.7: recursive make emits one
    // primary per subdirectory, so the SAME name is defined four times. Taking
    // the last dropped the project's namesake binary while reporting success.
    const RECURSIVE_PRIMARIES: &str = "\
bin_PROGRAMS = $(am__EXEEXT_1) $(am__EXEEXT_2)
bin_PROGRAMS = xz$(EXEEXT)
bin_PROGRAMS = lzmainfo$(EXEEXT)
lib_LTLIBRARIES = liblzma.la
EXEEXT =
xz_SOURCES = src/xz/main.c
lzmainfo_SOURCES = src/lzmainfo/lzmainfo.c
";

    #[test]
    fn a_primary_defined_in_several_subdirectories_keeps_every_target() {
        let names: Vec<String> = declared_targets(&parse_variables(RECURSIVE_PRIMARIES))
            .into_iter()
            .map(|t| t.name)
            .collect();
        assert_eq!(
            names,
            vec![
                "liblzma.la".to_string(),
                "lzmainfo".to_string(),
                "xz".to_string()
            ],
            "recursive make defines bin_PROGRAMS once per subdirectory; overwriting \
             silently drops every target but the last. Also: `$(am__EXEEXT_N)` is an \
             unexpanded reference, not a target name."
        );
    }

    // The other direction: accumulating is confined to primaries. A per-target
    // variable belongs to exactly one directory, so merging its definitions
    // would concatenate unrelated source lists.
    #[test]
    fn a_non_primary_variable_still_takes_the_last_definition() {
        let vars = parse_variables("xz_SOURCES = first.c\nxz_SOURCES = second.c\n");
        assert_eq!(
            vars.get("xz_SOURCES").map(String::as_str),
            Some("second.c"),
            "only primaries accumulate; a per-target variable keeps make's \
             last-assignment-wins"
        );
    }

    #[test]
    fn parses_the_real_command_stream_into_a_graph() {
        let graph = graph_from_captures();
        let names: Vec<&str> = graph.targets.iter().map(|t| t.name.as_str()).collect();
        // automake's own names, sanitised for Bazel but not shortened —
        // see target_label on why stripping `lib` collides.
        assert_eq!(
            names,
            vec!["greeter", "libgreet.a", "libshout.la"],
            "{graph:#?}"
        );

        let by_name = |n: &str| {
            graph
                .targets
                .iter()
                .find(|t| t.name == n)
                .unwrap_or_else(|| panic!("missing {n}"))
        };

        // noinst_LIBRARIES -> a static archive built by `ar`.
        let greet = by_name("libgreet.a");
        assert_eq!(greet.kind, TargetKind::Library);
        assert!(!greet.is_shared, "an ar archive is not shared");
        assert_eq!(greet.sources, vec!["src/greet.c"]);

        // lib_LTLIBRARIES -> a libtool library. This is the concept with no
        // CMake analogue, and the one the whole frontend was worth writing to
        // find out about.
        let shout = by_name("libshout.la");
        assert_eq!(shout.kind, TargetKind::Library);
        assert!(
            shout.is_shared,
            "LTLIBRARIES is libtool's form and builds a shared library — read \
             from the PRIMARY, not guessed from the .la suffix"
        );
        assert_eq!(shout.sources, vec!["src/shout.c"]);

        // bin_PROGRAMS -> an executable, with BOTH libraries as dependencies.
        // The edges come from the link line's inputs, which is the only place
        // the command stream states them.
        let greeter = by_name("greeter");
        assert_eq!(greeter.kind, TargetKind::Executable);
        assert_eq!(greeter.sources, vec!["src/main.c"]);
        assert_eq!(
            greeter.dependencies,
            vec!["libgreet.a", "libshout.la"],
            "both libraries are link inputs"
        );

        // `-I.` resolves TO the module root, which Bazel cannot express as an
        // includes entry — it is recorded as needs_root_include instead, and
        // codegen stages the public headers into _include/. Same decision the
        // CMake frontend makes, for the same reason.
        //
        // `-I.` is the ONLY include this fixture's compiles carry, so both
        // lists are empty. An earlier version of this capture invented an
        // `-Isrc` and asserted `greet.includes == ["src"]`; the assertion held
        // only because the input had been written to satisfy it. Per-target
        // include attribution is genuinely exercised by
        // `a_commands_paths_resolve_against_the_directory_it_ran_in`, whose
        // stream carries two different `-I` values.
        assert!(
            greet.includes.is_empty(),
            "-I. is the module root, not an includes entry: {greet:#?}"
        );
        assert!(greet.needs_root_include, "-I. must set it: {greet:#?}");
        assert!(greeter.includes.is_empty(), "{greeter:#?}");
        assert!(greeter.needs_root_include, "{greeter:#?}");

        // include_HEADERS is automake's statement that a header is public —
        // the same claim CMake makes with install(FILES ... DESTINATION
        // include). greet.h is listed in libgreet_a_SOURCES AND installed, so
        // it is public; nothing else is.
        assert_eq!(greet.public_headers, vec!["src/greet.h"], "{greet:#?}");
        assert!(greeter.public_headers.is_empty(), "{greeter:#?}");

        // configure puts its own substitutions on every compile line, and they
        // carry QUOTES. This is where the value that motivated
        // `codegen::escape_starlark` actually comes from, so the capture is
        // the honest place to pin its shape: emitted raw into a Starlark
        // string, `PACKAGE_NAME="greeter"` closes that string early and the
        // generated module stops parsing.
        assert!(
            greet
                .local_defines
                .contains(&"PACKAGE_NAME=\"greeter\"".to_string()),
            "the define reaches the model with its quotes intact, unescaped — \
             escaping is codegen's job and happens at render time: {:#?}",
            greet.local_defines
        );
    }

    // The point of this frontend: codegen has only ever seen CMake. If the
    // model boundary is real, an Autotools graph renders through it with no
    // change to codegen at all.
    #[test]
    fn an_autotools_graph_renders_through_unmodified_codegen() {
        let graph = graph_from_captures();
        let rendered = codegen::render(&graph).build_bazel;

        assert!(
            rendered.contains("cc_library(\n    name = \"libgreet.a\","),
            "the static archive becomes a cc_library:\n{rendered}"
        );
        assert!(
            rendered.contains("cc_shared_library(\n    name = \"libshout.la_shared\","),
            "and the libtool library gets the shared-library treatment zlib \
             drove, with no autotools-specific codegen:\n{rendered}"
        );
        assert!(
            rendered.contains("cc_binary(\n    name = \"greeter\","),
            "the program becomes a cc_binary:\n{rendered}"
        );
        assert!(
            rendered.contains("\":libgreet.a\",") && rendered.contains("\":libshout.la\","),
            "with both library edges:\n{rendered}"
        );
    }
}
