//! Libtool's artifact layer: what `make` actually leaves on disk when a
//! project uses libtool, as opposed to what it says it built.
//!
//! Its own module because it is a THIRD input to the Autotools conversion,
//! read a different way from the other two. The build's stdout and `make -p`
//! are interrogated; these files are read off disk after the fact, and only
//! ground-truth capture needs them. Keeping them in `main` put build-system
//! knowledge in the driver, whose contract is to consume a `Discovery`
//! without knowing which frontend produced it (bzl-573).
//!
//! Nothing here dispatches on the frontend. Every function keys on what an
//! artifact IS — its extension, its first three lines — because a CMake
//! project could in principle produce a libtool artifact too.

use std::fs;
use std::path::{Path, PathBuf};

/// The file to capture as ground truth for `artifact`, resolving libtool's
/// wrapper indirection.
///
/// When a program links a libtool library, `make` leaves a **shell wrapper**
/// at the program's output path and the real ELF binary in a sibling
/// `.libs/`. The wrapper's only job is to set `LD_LIBRARY_PATH` and re-exec
/// the real one, so copying it produces a script that looks for a directory
/// nobody copied — reported as a missing path under `.libs/`, several steps
/// from the cause. See
/// docs/lore/libtool-puts-a-wrapper-script-where-the-binary-goes.md.
///
/// Detected by reading the file rather than by testing whether `.libs/`
/// exists: `.libs/` is present for every libtool target including ones whose
/// output path already holds the real binary, so its existence answers a
/// different question. libtool announces itself on line 2 of the wrapper.
pub(crate) fn ground_truth_source(build_dir: &Path, artifact: &str) -> PathBuf {
    let direct = build_dir.join(artifact);
    if !is_libtool_wrapper(&direct) {
        return direct;
    }
    let Some(name) = Path::new(artifact).file_name() else {
        return direct;
    };
    let real = direct.with_file_name(".libs").join(name);
    // Falls back to the wrapper when the real binary is missing. A wrapper
    // that cannot run fails the comparison loudly; guessing at a path that
    // does not exist would fail the CONVERSION, which is worse for a
    // difference this function only detects heuristically.
    if real.is_file() {
        real
    } else {
        direct
    }
}

/// The real shared library a libtool `.la` control file stands for, as a
/// build-dir-relative path, or `None` when it names no shared library.
///
/// A `.la` is not a library: it is a text control file, and the real
/// `libfoo.so.N.N.N` lives in a sibling `.libs/`. Rather than assume that
/// layout, this reads the `.la`'s own `dlname=` field, which libtool writes
/// for exactly this purpose and which is empty for a static-only library.
///
/// Returns (where the library IS, the name to STAGE it under). The second is
/// a bare filename, so the chain lands at the `ground_truth/` ROOT — which is
/// where CMake projects' libraries already land, and the only directory on
/// every binary's search path. The comparison script finds a ground-truth
/// library by walking UP from the binary, so both libtool's private `.libs/`
/// and the `.la`'s own `src/liblzma/` are invisible to a binary in a SIBLING
/// directory like `src/xz/`: the loader then silently falls back to the
/// host's copy, and the comparison runs a different liblzma against the Bazel
/// build without saying so. See
/// docs/lore/ground-truth-so-lives-at-the-root-not-beside-the-binary.md.
pub(crate) fn libtool_shared_library(build_dir: &Path, artifact: &str) -> Option<(String, String)> {
    if !artifact.ends_with(".la") {
        return None;
    }
    let text = fs::read_to_string(build_dir.join(artifact)).ok()?;
    let dlname = text
        .lines()
        .find_map(|l| l.strip_prefix("dlname="))?
        .trim_matches('\'');
    if dlname.is_empty() {
        return None;
    }
    let dir = Path::new(artifact).parent().unwrap_or(Path::new(""));
    Some((
        dir.join(".libs")
            .join(dlname)
            .to_string_lossy()
            .into_owned(),
        dlname.to_string(),
    ))
}

/// Whether `path` is a libtool wrapper script rather than the built artifact.
pub(crate) fn is_libtool_wrapper(path: &Path) -> bool {
    let Ok(text) = fs::read_to_string(path) else {
        // Unreadable as UTF-8 means a real binary, which is the common case.
        return false;
    };
    text.starts_with("#!")
        && text
            .lines()
            .take(3)
            .any(|l| l.contains("wrapper script for") || l.contains("Generated by libtool"))
}


#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// A directory no other test or run will pick, created fresh. See the
    /// same helper in `main.rs` for why pid alone is not enough: the suite
    /// runs its tests as THREADS of one process.
    fn unique_temp_dir(name: &str) -> PathBuf {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "bzlf_{name}_{}_{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::remove_dir_all(&dir).ok();
        dir
    }

    // libtool leaves a SHELL WRAPPER where the binary goes and the real ELF in
    // a sibling `.libs/`. Copying the wrapper produced a ground-truth artifact
    // whose only job was to find a directory nobody copied, reported as a
    // missing path under `.libs/` — several steps from the cause. See
    // docs/lore/libtool-puts-a-wrapper-script-where-the-binary-goes.md.
    #[test]
    fn a_libtool_wrapper_resolves_to_the_real_binary_beside_it() {
        let dir = unique_temp_dir("a_libtool_wrapper_resolves_to_the_real_binary_beside_it");
        // A fresh directory per invocation. Two earlier attempts were not
        // unique enough and both failed intermittently: `line!()` shifts
        // whenever a comment above it is edited, so a run inherits a DIFFERENT
        // test's leftover tree; and pid+test-name still collides because the
        // suite runs its tests as THREADS of one process, so a sibling's
        // create_dir_all races this one's remove_dir_all.
        let bin_dir = dir.join("src/xz");
        fs::create_dir_all(bin_dir.join(".libs")).unwrap();
        // Line 2 is how libtool announces itself; the shebang alone is not
        // enough, since a project can legitimately install a script.
        fs::write(
            bin_dir.join("xz"),
            b"#! /bin/bash\n# xz - temporary wrapper script for .libs/xz\nexec .libs/xz\n",
        )
        .unwrap();
        fs::write(bin_dir.join(".libs").join("xz"), b"\x7fELF-not-really\n").unwrap();

        assert_eq!(
            ground_truth_source(&dir, "src/xz/xz"),
            bin_dir.join(".libs").join("xz"),
            "the wrapper is not the artifact; the real binary is"
        );
    }

    // The other direction, and the reason detection reads the FILE rather than
    // testing whether `.libs/` exists: `.libs/` is present for every libtool
    // target, including ones whose output path already holds the real binary.
    #[test]
    fn a_real_binary_is_captured_even_when_a_libs_dir_exists() {
        let dir = unique_temp_dir("a_real_binary_is_captured_even_when_a_libs_dir_exists");
        // Named for the test and cleared first. `line!()` was tried and is
        // not an identity: any edit above shifts it, so a run can inherit a
        // DIFFERENT test's leftover tree — and create_dir_all reuses it
        // happily, which surfaced as this test failing on a file it had just
        // written.
        let bin_dir = dir.join("src/tool");
        fs::create_dir_all(bin_dir.join(".libs")).unwrap();
        fs::write(bin_dir.join("tool"), b"\x7fELF-the-real-one\n").unwrap();
        fs::write(bin_dir.join(".libs").join("tool"), b"\x7fELF-a-decoy\n").unwrap();

        assert_eq!(
            ground_truth_source(&dir, "src/tool/tool"),
            bin_dir.join("tool"),
            "no wrapper means no indirection, whatever .libs/ happens to hold"
        );
    }

    // A `.la` is a text control file, not a library. Its `dlname=` names the
    // real shared object — read rather than guessed, because it is empty for a
    // static-only library and the layout is libtool's to change.
    #[test]
    fn a_la_file_names_its_shared_library_and_stages_it_at_the_root() {
        let dir = unique_temp_dir("a_la_file_names_its_shared_library_and_stages_it_at_the_root");
        // Named for the test and cleared first. `line!()` was tried and is
        // not an identity: any edit above shifts it, so a run can inherit a
        // DIFFERENT test's leftover tree — and create_dir_all reuses it
        // happily, which surfaced as this test failing on a file it had just
        // written.
        fs::remove_dir_all(&dir).ok();
        let lib_dir = dir.join("src/liblzma");
        fs::create_dir_all(&lib_dir).unwrap();
        fs::write(
            lib_dir.join("liblzma.la"),
            b"dlname='liblzma.so.5'\nlibrary_names='liblzma.so.5.4.7 liblzma.so.5 liblzma.so'\n",
        )
        .unwrap();

        assert_eq!(
            libtool_shared_library(&dir, "src/liblzma/liblzma.la"),
            Some((
                "src/liblzma/.libs/liblzma.so.5".to_string(),
                "liblzma.so.5".to_string()
            )),
            "found in libtool's private .libs/, but staged at the ground_truth \
             ROOT — the comparison script walks UP from the binary, so a chain \
             under src/liblzma/ is invisible to a binary in the SIBLING \
             src/xz/ and the loader silently uses the host's copy instead"
        );
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_static_only_la_names_no_shared_library() {
        let dir = unique_temp_dir("a_static_only_la_names_no_shared_library");
        // Named for the test and cleared first. `line!()` was tried and is
        // not an identity: any edit above shifts it, so a run can inherit a
        // DIFFERENT test's leftover tree — and create_dir_all reuses it
        // happily, which surfaced as this test failing on a file it had just
        // written.
        fs::remove_dir_all(&dir).ok();
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("libfoo.la"), b"dlname=\'\'\nold_library=\'libfoo.a\'\n").unwrap();

        assert_eq!(
            libtool_shared_library(&dir, "libfoo.la"),
            None,
            "an empty dlname means the library is static-only, so there is no \
             .so chain to stage"
        );
        fs::remove_dir_all(&dir).ok();
    }
}
