load("//translator/build_defs:convert_cmake_project.bzl", "convert_cmake_project")

convert_cmake_project(
    name = "converted",
    srcs = ["CMakeLists.txt"] + glob([
        "src/**",
        "include/**",
    ]),
    expected_targets = ["hello"],
    module_name = "with_library",
    source_dir = package_name(),
    visibility = ["//translator/tests:__pkg__"],
)
