#!/usr/bin/env python3
"""Unit tests for tools/catalog/harvest.py.

    python3 tools/catalog/harvest_test.py

The inputs are configure fragments in both autoconf dialects the corpus
carries (2.69: ac_fn_c_check_decl, `do :` on its own line; 2.71:
ac_fn_check_decl with two trailing arguments), so the test can fail on the
spelling difference that would otherwise drop every declaration of one
dialect. Host compiles are replaced by a fake that answers from a table, so
the header choice and the absent/present verdicts are pinned without a
compiler.
"""
import os
import re
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import harvest as H  # noqa: E402

CONFIGURE_269 = r'''
# Generated by GNU Autoconf 2.69 for libevent 2.1.12-stable.
for ac_header in sys/types.h \
  sys/epoll.h \
  port.h
do :
  as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
done
for ac_func in  \
  accept4 \
  kqueue \
  mmap
do :
  ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
done
  for ac_func in clock_gettime
do :
  ac_fn_c_check_func "$LINENO" "clock_gettime" "ac_cv_func_clock_gettime"
done
ac_fn_c_check_type "$LINENO" "uint16_t" "ac_cv_type_uint16_t" "$ac_includes_default"
ac_fn_c_check_member "$LINENO" "struct sockaddr_in" "sin_len" "ac_cv_member_struct_sockaddr_in_sin_len" "#include <sys/types.h>
#ifdef HAVE_NETINET_IN_H
#include <netinet/in.h>
#endif
"
	ac_fn_c_check_decl "$LINENO" "CTL_KERN" "ac_cv_have_decl_CTL_KERN" "#include <sys/types.h>
#include <sys/sysctl.h>
"
  if ac_fn_c_compute_int "$LINENO" "(long int) (sizeof (pthread_t))" "ac_cv_sizeof_pthread_t"        "$ac_includes_default
      #include <pthread.h>
"; then :
  if ac_fn_c_compute_int "$LINENO" "(long int) offsetof (ac__type_alignof_, y)" "ac_cv_alignof_double"        "$ac_includes_default
#ifndef offsetof
# define offsetof(type, member) ((char *) &((type *) 0)->member - (char *) 0)
#endif
typedef struct { char x; double y; } ac__type_alignof_;"; then :
# Check whether --enable-openssl was given.
if test "${enable_openssl+set}" = set; then :
$as_echo "#define HAVE_OPENSSL 1" >>confdefs.h
fi
'''

CONFIGURE_271 = r'''
# Generated by GNU Autoconf 2.71 for XZ Utils 5.6.2.
ac_fn_c_check_header_compile "$LINENO" "sys/capsicum.h" "ac_cv_header_sys_capsicum_h" "$ac_includes_default"
for ac_func in strcasecmp; do :
  ac_fn_c_check_func "$LINENO" "strcasecmp" "ac_cv_func_strcasecmp"
done
ac_fn_check_decl "$LINENO" "strncasecmp" "ac_cv_have_decl_strncasecmp" "$ac_includes_default" "$ac_c_undeclared_builtin_options" "CFLAGS"
ac_fn_c_check_type "$LINENO" "KAFFINITY" "ac_cv_type_KAFFINITY" "#include <windows.h>
"
'''


def by_macro(entries):
    return {e.macro: e for e in entries}


class ParseTest(unittest.TestCase):
    def test_269_dialect_every_kind(self):
        got = by_macro(H.harvest(CONFIGURE_269))
        self.assertEqual(got["HAVE_SYS_EPOLL_H"].subject, "sys/epoll.h", got.keys())
        self.assertEqual(got["HAVE_PORT_H"].kind, "header")
        self.assertEqual({"accept4", "kqueue", "mmap", "clock_gettime"},
                         {e.subject for e in got.values() if e.kind == "symbol" and not e.macro.startswith("HAVE_DECL_")})
        self.assertEqual(got["HAVE_UINT16_T"].headers, H.DEFAULT_INCLUDES)
        m = got["HAVE_STRUCT_SOCKADDR_IN_SIN_LEN"]
        self.assertEqual((m.kind, m.subject, m.member, m.headers),
                         ("struct_member", "struct sockaddr_in", "sin_len", ["sys/types.h", "netinet/in.h"]))
        d = got["HAVE_DECL_CTL_KERN"]
        self.assertEqual((d.kind, d.subject, d.headers), ("symbol", "CTL_KERN", ["sys/types.h", "sys/sysctl.h"]))
        s = got["SIZEOF_PTHREAD_T"]
        self.assertEqual((s.kind, s.subject), ("sizeof", "pthread_t"))
        self.assertEqual(s.headers, H.DEFAULT_INCLUDES + ["pthread.h"])
        a = got["ALIGNOF_DOUBLE"]
        self.assertEqual((a.kind, a.subject, a.headers), ("alignof", "double", H.DEFAULT_INCLUDES),
                         "AC_CHECK_ALIGNOF names its type only in the probe's typedef")
        self.assertNotIn("HAVE_DO", got, "the loop keyword is not a function")
        self.assertNotIn("HAVE__AC_FUNC", got)

    def test_271_dialect(self):
        got = by_macro(H.harvest(CONFIGURE_271))
        self.assertEqual(got["HAVE_SYS_CAPSICUM_H"].subject, "sys/capsicum.h")
        self.assertEqual(got["HAVE_STRCASECMP"].subject, "strcasecmp", "`; do` on the loop line")
        self.assertEqual(got["HAVE_DECL_STRNCASECMP"].headers, H.DEFAULT_INCLUDES,
                         "2.71's ac_fn_check_decl carries two extra arguments")
        self.assertEqual(got["HAVE_KAFFINITY"].headers, ["windows.h"])

    def test_project_banner(self):
        self.assertEqual(H.project_of(CONFIGURE_269), "libevent 2.1.12-stable")
        self.assertEqual(H.project_of(CONFIGURE_271), "XZ Utils 5.6.2", "a project name with a space")

    def test_as_tr_cpp(self):
        self.assertEqual(H.as_tr_cpp("struct sockaddr_in"), "STRUCT_SOCKADDR_IN")
        self.assertEqual(H.as_tr_cpp("void *"), "VOID_P")
        self.assertEqual(H.as_tr_cpp("netinet/ip_icmp.h"), "NETINET_IP_ICMP_H")


class SelectTest(unittest.TestCase):
    def test_partitions(self):
        entries = H.harvest(CONFIGURE_269)
        wanted = {"HAVE_SYS_EPOLL_H", "HAVE_KQUEUE", "HAVE_OPENSSL", "HAVE_CUSTOM_PROBE", "HAVE_UINT16_T"}
        existing = {"HAVE_UINT16_T"}
        flagged = set(H.flag_macros(CONFIGURE_269))
        new, skipped = H.select(entries, wanted, existing, flagged)
        self.assertEqual({e.macro for e in new}, {"HAVE_SYS_EPOLL_H", "HAVE_KQUEUE"})
        self.assertEqual(skipped["in catalog"], ["HAVE_UINT16_T"])
        self.assertIn("HAVE_PORT_H", skipped["not in template"])
        self.assertEqual(skipped["no check site"], ["HAVE_CUSTOM_PROBE", "HAVE_OPENSSL"],
                         "what remains for the escalation path, flag macros included")

    def test_no_template_means_everything(self):
        new, skipped = H.select(H.harvest(CONFIGURE_269), None, set(), set())
        self.assertEqual(skipped["not in template"], [])
        self.assertEqual(skipped["no check site"], [])
        self.assertEqual(len(new), 12, sorted(e.macro for e in new))


class FakeCompiler:
    """Answers a probe from what each header 'declares'; `run_int` is fixed."""

    DECLARES = {
        "sys/socket.h": {"accept4"},
        "sys/mman.h": {"mmap"},
        "unistd.h": {"mmap", "accept4"},  # a catch-all that must NOT win
        "time.h": {"clock_gettime"},
        "sys/epoll.h": set(),
        "sys/types.h": set(),
        "netinet/in.h": set(),
        "pthread.h": {"pthread_t"},
        "stdint.h": {"uint16_t"},
        "sys/sysctl.h": set(),
    }

    BUILTIN = {"int", "long", "void *", "double"}

    def compiles(self, source, link=False, defines=()):
        headers = re.findall(r'#include <([^>]+)>', source)
        if any(h not in self.DECLARES for h in headers):
            return False  # a header this host lacks
        declared = set().union(*(self.DECLARES[h] for h in headers)) if headers else set()
        declared |= self.BUILTIN
        for pattern in (r'\(&(\w+)\)', r'sizeof\(s\.(\w+)\)', r'sizeof\(([^)]+)\)', r'_Alignof\(([^)]+)\)'):
            m = re.search(pattern, source)
            if m:
                return m.group(1) in declared
        return True  # a header probe: nothing but includes

    def run_int(self, source, defines=()):
        return 8

    # Where the preprocessor says each symbol is really declared, when a
    # catch-all reached it transitively.
    DECLARED_IN = {("mmap", "unistd.h"): "sys/mman.h"}

    def declaring_header(self, symbol, header, defines=()):
        return self.DECLARED_IN.get((symbol, header))


class VerifyTest(unittest.TestCase):
    def verified(self):
        entries = [e for e in H.harvest(CONFIGURE_269 + CONFIGURE_271)]
        return by_macro(H.verify(entries, FakeCompiler()))

    def test_symbol_header_is_the_specific_one(self):
        got = self.verified()
        self.assertEqual((got["HAVE_MMAP"].headers, got["HAVE_MMAP"].present), (["sys/mman.h"], True))
        self.assertEqual(got["HAVE_MMAP"].note, "", "found directly, no detour to report")
        self.assertEqual(got["HAVE_ACCEPT4"].headers, ["sys/socket.h"], "not unistd.h, which also declares it here")
        self.assertEqual(got["HAVE_CLOCK_GETTIME"].source, "table")

    def test_absent_symbol_from_the_table_is_marked_unverifiable(self):
        k = self.verified()["HAVE_KQUEUE"]
        self.assertEqual((k.headers, k.present), (["sys/event.h"], False))
        self.assertIn("unverifiable", k.note)

    def test_symbol_nobody_declares_is_unresolved(self):
        s = self.verified()["HAVE_STRCASECMP"]
        self.assertEqual((s.headers, s.present), ([], False))
        self.assertTrue(s.note.startswith("HEADER?"), s.note)
        self.assertEqual([e.subject for e in H.unresolved([s])], ["strcasecmp"])

    def test_a_transitively_reached_symbol_takes_its_declaring_header(self):
        fake = FakeCompiler()
        fake.DECLARES = dict(FakeCompiler.DECLARES)
        del fake.DECLARES["sys/mman.h"]  # the catch-all is the first hit now
        fake.DECLARES["sys/mman.h"] = {"mmap"}
        fake.DECLARES = {**fake.DECLARES, "sys/mman.h": {"mmap"}}
        # Make unistd.h the first candidate that compiles by removing the
        # specific header from the search order.
        saved = H.SYMBOL_HEADER_CANDIDATES[:]
        H.SYMBOL_HEADER_CANDIDATES[:] = [h for h in saved if h != "sys/mman.h"]
        try:
            got = by_macro(H.verify(H.harvest(CONFIGURE_269), fake))
        finally:
            H.SYMBOL_HEADER_CANDIDATES[:] = saved
        self.assertEqual(got["HAVE_MMAP"].headers, ["sys/mman.h"],
                         "unistd.h compiled first, but the declaration lives in sys/mman.h")
        self.assertEqual(got["HAVE_MMAP"].note, "declared in sys/mman.h, first reached through unistd.h")

    def test_override_wins(self):
        entries = H.harvest(CONFIGURE_271)
        got = by_macro(H.verify(entries, FakeCompiler(), {"strcasecmp": "sys/socket.h"}))
        self.assertEqual((got["HAVE_STRCASECMP"].headers, got["HAVE_STRCASECMP"].source), (["sys/socket.h"], "supplied"))

    def test_stated_includes_minimise_to_one(self):
        got = self.verified()
        self.assertEqual(got["HAVE_UINT16_T"].headers, ["stdint.h"], "not all ten of $ac_includes_default")
        self.assertEqual(got["SIZEOF_PTHREAD_T"].headers, ["pthread.h"])
        self.assertEqual(got["SIZEOF_PTHREAD_T"].value, 8)
        self.assertEqual((got["ALIGNOF_DOUBLE"].headers, got["ALIGNOF_DOUBLE"].value), ([], 8),
                         "a builtin type needs no header; the fake answers 8 for every run")
        self.assertEqual(H.catalog_line(got["ALIGNOF_DOUBLE"]), '("double", [], "ALIGNOF_DOUBLE"),')
        self.assertEqual(H.template_line(got["ALIGNOF_DOUBLE"]), "#define ALIGNOF_DOUBLE @ALIGNOF_DOUBLE@")
        self.assertEqual(H.assertion_line(got["ALIGNOF_DOUBLE"]), '"#define ALIGNOF_DOUBLE 8",')

    def test_absent_type_keeps_only_the_includable_stated_headers(self):
        got = self.verified()
        self.assertEqual((got["HAVE_KAFFINITY"].headers, got["HAVE_KAFFINITY"].present), (["windows.h"], False),
                         "windows.h is not includable here, but it is all configure stated, so it stays")
        m = got["HAVE_STRUCT_SOCKADDR_IN_SIN_LEN"]
        self.assertEqual((m.headers, m.present), (["sys/types.h", "netinet/in.h"], False))

    def test_decl_present_and_absent(self):
        got = self.verified()
        self.assertEqual(got["HAVE_DECL_CTL_KERN"].present, False)
        self.assertEqual(H.assertion_line(got["HAVE_DECL_CTL_KERN"]), '"#define HAVE_DECL_CTL_KERN 0",')


class RenderAndApplyTest(unittest.TestCase):
    def entries(self):
        got = by_macro(H.verify(H.harvest(CONFIGURE_269), FakeCompiler()))
        return [got[m] for m in ("HAVE_SYS_EPOLL_H", "HAVE_KQUEUE", "HAVE_UINT16_T",
                                 "HAVE_STRUCT_SOCKADDR_IN_SIN_LEN", "SIZEOF_PTHREAD_T", "HAVE_DECL_CTL_KERN")]

    def test_lines(self):
        e = by_macro(self.entries())
        self.assertEqual(H.catalog_line(e["HAVE_SYS_EPOLL_H"]), '("sys/epoll.h", "HAVE_SYS_EPOLL_H"),')
        self.assertEqual(H.catalog_line(e["HAVE_KQUEUE"]), '("kqueue", ["sys/event.h"], "HAVE_KQUEUE"),')
        self.assertEqual(H.catalog_line(e["HAVE_STRUCT_SOCKADDR_IN_SIN_LEN"]),
                         '("struct sockaddr_in", "sin_len", ["sys/types.h", "netinet/in.h"], "HAVE_STRUCT_SOCKADDR_IN_SIN_LEN"),')
        self.assertEqual(H.template_line(e["SIZEOF_PTHREAD_T"]), "#define SIZEOF_PTHREAD_T @SIZEOF_PTHREAD_T@")
        self.assertEqual(H.template_line(e["HAVE_DECL_CTL_KERN"]), "#undef HAVE_DECL_CTL_KERN")
        self.assertEqual(H.template_line(e["HAVE_KQUEUE"]), "#cmakedefine HAVE_KQUEUE")
        self.assertEqual(H.assertion_line(e["HAVE_KQUEUE"]), '"/* #undef HAVE_KQUEUE */",')
        self.assertEqual(H.assertion_line(e["HAVE_SYS_EPOLL_H"]), '"#define HAVE_SYS_EPOLL_H",')
        self.assertEqual(H.assertion_line(e["SIZEOF_PTHREAD_T"]), '"#define SIZEOF_PTHREAD_T 8",')

    def test_report_names_the_unverifiable(self):
        text = H.render_report("p", self.entries(), {"in catalog": ["X"], "not in template": [], "flag-driven": ["HAVE_OPENSSL"], "no check site": []}, True)
        self.assertIn("HAVE_KQUEUE", text)
        self.assertIn("unverifiable", text)
        self.assertIn("skipped, flag-driven: 1\n  HAVE_OPENSSL", text)

    CATALOG = '''cc_config_catalog(
    headers = [
        ("a.h", "HAVE_A_H"),
    ],
    struct_members = [
    ],
    symbols = [
        ("x", ["x.h"], "HAVE_X"),
        (
            "CTL_HW",
            [
                "sys/types.h",
                "sys/sysctl.h",
            ],
            "HAVE_DECL_CTL_HW",
        ),
    ],
    type_exists = [
    ],
    types = [
        ("int", [], "SIZEOF_INT"),
    ],
)

config_header(
    name = "catalog_smoke_h",
    probes = [
        ":have_a_h",
    ],
    template = "t.h.in",
)

assert_config_header_test(
    name = "catalog_smoke_test",
    must_contain = [
        "#define HAVE_A_H",
    ],
    must_not_contain = [
        "@SIZEOF_LONG@",
    ],
)
'''
    DEFINES = 'const CATALOG_DEFINES: &[&str] = &[\n    "HAVE_A_H",\n];\nfn other() -> &[&str] { &[\n];}\n'

    def test_apply_writes_all_four_places_or_none(self):
        new = self.entries()
        with tempfile.TemporaryDirectory() as root:
            os.makedirs(os.path.join(root, "cc_config/catalog"))
            os.makedirs(os.path.join(root, "translator/src"))
            paths = {
                "cc_config/catalog/BUILD.bazel": self.CATALOG,
                "translator/src/configure_file.rs": self.DEFINES,
                "cc_config/catalog/testdata_catalog_smoke.h.in": "#cmakedefine HAVE_A_H",
            }
            for rel, content in paths.items():
                with open(os.path.join(root, rel), "w") as fh:
                    fh.write(content)
            H.apply_all(root, new, "BANNER")
            cat = open(os.path.join(root, "cc_config/catalog/BUILD.bazel")).read()
            defs = open(os.path.join(root, "translator/src/configure_file.rs")).read()
            tpl = open(os.path.join(root, "cc_config/catalog/testdata_catalog_smoke.h.in")).read()
        # Each entry lands in ITS section, after the existing entries.
        self.assertIn('        ("a.h", "HAVE_A_H"),\n        # BANNER\n        ("sys/epoll.h", "HAVE_SYS_EPOLL_H"),\n    ],', cat)
        self.assertIn('    struct_members = [\n        # BANNER\n        ("struct sockaddr_in", "sin_len"', cat)
        self.assertIn('("kqueue", ["sys/event.h"], "HAVE_KQUEUE"),  # absent on this host', cat)
        self.assertIn('            "HAVE_DECL_CTL_HW",\n        ),\n        # BANNER\n        ("kqueue"', cat,
                      "the block goes after the LAST entry, past a nested headers list that also closes with `],`")
        self.assertIn('("CTL_KERN", ["sys/types.h", "sys/sysctl.h"], "HAVE_DECL_CTL_KERN"),  # absent on this host', cat)
        self.assertIn('    types = [\n        ("int", [], "SIZEOF_INT"),\n        # BANNER\n        ("pthread_t", ["pthread.h"], "SIZEOF_PTHREAD_T"),', cat)
        self.assertIn('        ":have_a_h",\n        # BANNER\n        ":have_sys_epoll_h",\n        ":have_kqueue",', cat)
        self.assertIn('        "#define HAVE_A_H",\n        # BANNER\n        "#define HAVE_SYS_EPOLL_H",\n        "/* #undef HAVE_KQUEUE */",', cat)
        self.assertIn('        "#define HAVE_DECL_CTL_KERN 0",\n    ],\n    must_not_contain', cat)
        # CATALOG_DEFINES grows; the unrelated array below it does not.
        self.assertIn('    "HAVE_A_H",\n    // BANNER\n    "HAVE_SYS_EPOLL_H",\n    "HAVE_KQUEUE",', defs)
        self.assertIn('    "HAVE_DECL_CTL_KERN",\n];\nfn other', defs)
        self.assertEqual(tpl.count("\n"), 7)
        self.assertIn("#cmakedefine HAVE_A_H\n#cmakedefine HAVE_SYS_EPOLL_H\n", tpl)
        self.assertIn("#define SIZEOF_PTHREAD_T @SIZEOF_PTHREAD_T@\n#undef HAVE_DECL_CTL_KERN\n", tpl)

    def test_apply_with_a_missing_anchor_writes_nothing(self):
        new = self.entries()
        with tempfile.TemporaryDirectory() as root:
            os.makedirs(os.path.join(root, "cc_config/catalog"))
            os.makedirs(os.path.join(root, "translator/src"))
            with open(os.path.join(root, "cc_config/catalog/BUILD.bazel"), "w") as fh:
                fh.write(self.CATALOG)
            with open(os.path.join(root, "translator/src/configure_file.rs"), "w") as fh:
                fh.write("no defines array here\n")
            with open(os.path.join(root, "cc_config/catalog/testdata_catalog_smoke.h.in"), "w") as fh:
                fh.write("")
            with self.assertRaises(ValueError):
                H.apply_all(root, new, "BANNER")
            self.assertEqual(open(os.path.join(root, "cc_config/catalog/BUILD.bazel")).read(), self.CATALOG)
            self.assertEqual(open(os.path.join(root, "cc_config/catalog/testdata_catalog_smoke.h.in")).read(), "")


if __name__ == "__main__":
    unittest.main()
